// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AllTypesSyntax2.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes {

  /// <summary>Holder for reflection information generated from AllTypesSyntax2.proto</summary>
  public static partial class AllTypesSyntax2Reflection {

    #region Descriptor
    /// <summary>File descriptor for AllTypesSyntax2.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AllTypesSyntax2Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVBbGxUeXBlc1N5bnRheDIucHJvdG8SRWNvbS5hbWF6b25hd3Muc2Vydmlj",
            "ZXMuc2NoZW1hcmVnaXN0cnkudGVzdHMucHJvdG9idWYuc3ludGF4Mi5hbGx0",
            "eXBlcxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90bxoXZ29vZ2xl",
            "L3R5cGUvbW9uZXkucHJvdG8ikAkKCEFsbFR5cGVzEhcKCnN0cmluZ1R5cGUY",
            "UCACKAlSA0FfQRIUCghieXRlVHlwZRhiIAEoDEICGAESEgoIb25lT2ZJbnQY",
            "ASABKAVIABIoCgpvbmVPZk1vbmV5GAMgASgLMhIuZ29vZ2xlLnR5cGUuTW9u",
            "ZXlIABIWCg5yZXBlYXRlZFN0cmluZxgEIAMoCRIbChJyZXBlYXRlZFBhY2tl",
            "ZEludHMY7AMgAygJEhMKCWludDY0Qml0MRgFIAEoA0gBEi8KEWFub3RoZXJP",
            "bmVPZk1vbmV5GAYgASgLMhIuZ29vZ2xlLnR5cGUuTW9uZXlIARIUCglvbmVP",
            "ZkJvb2wY7wEgASgISAESGAoQb3B0aW9uYWxTZml4ZWQzMhhjIAIoDxIgChdh",
            "bm90aGVyT3B0aW9uYWxTZml4ZWQzMhjgByABKA8SGQoQb3B0aW9uYWxTZml4",
            "ZWQ2NBjfByACKBASXwoHYW5FbnVtMhjuDiACKA4yTS5jb20uYW1hem9uYXdz",
            "LnNlcnZpY2VzLnNjaGVtYXJlZ2lzdHJ5LnRlc3RzLnByb3RvYnVmLnN5bnRh",
            "eDIuYWxsdHlwZXMuQW5FbnVtEhMKCnVpbnQ2NFR5cGUY4QcgASgEEhIKCWlu",
            "dDMyVHlwZRjiByACKA0SEwoKc2ludDMyVHlwZRjjByACKBESEwoKc2ludDY0",
            "VHlwZRjkByACKBISFAoLZml4ZWQzMlR5cGUY5QcgASgHEhQKC2ZpeGVkNjRU",
            "eXBlGOYHIAIoBhJ3Cg5uZXN0ZWRNZXNzYWdlMRjGASACKAsyXi5jb20uYW1h",
            "em9uYXdzLnNlcnZpY2VzLnNjaGVtYXJlZ2lzdHJ5LnRlc3RzLnByb3RvYnVm",
            "LnN5bnRheDIuYWxsdHlwZXMuQWxsVHlwZXMuTmVzdGVkTWVzc2FnZTESdgoL",
            "YUNvbXBsZXhNYXAY2hIgAygLMmAuY29tLmFtYXpvbmF3cy5zZXJ2aWNlcy5z",
            "Y2hlbWFyZWdpc3RyeS50ZXN0cy5wcm90b2J1Zi5zeW50YXgyLmFsbHR5cGVz",
            "LkFsbFR5cGVzLkFDb21wbGV4TWFwRW50cnkSXwoHYW5FbnVtMRjPDyABKA4y",
            "TS5jb20uYW1hem9uYXdzLnNlcnZpY2VzLnNjaGVtYXJlZ2lzdHJ5LnRlc3Rz",
            "LnByb3RvYnVmLnN5bnRheDIuYWxsdHlwZXMuQW5FbnVtGjoKDk5lc3RlZE1l",
            "c3NhZ2UxEhQKDGZsb2F0aW5nVHlwZRhkIAEoAhISCgpkb3VibGVUeXBlGGUg",
            "AigBGqABChBBQ29tcGxleE1hcEVudHJ5EgsKA2tleRgBIAEoBRJ7CgV2YWx1",
            "ZRgCIAEoCzJsLmNvbS5hbWF6b25hd3Muc2VydmljZXMuc2NoZW1hcmVnaXN0",
            "cnkudGVzdHMucHJvdG9idWYuc3ludGF4Mi5hbGx0eXBlcy5Bbm90aGVyVG9w",
            "TGV2ZWxNZXNzYWdlLk5lc3RlZE1lc3NhZ2UyOgI4AUIJCgdhT25lT2YxQgkK",
            "B2FPbmVPZjJKCAignAEQpZwBImYKD1RvcExldmVsTWVzc2FnZRIPCgdhbklu",
            "dDMyGAEgASgFEhgKDHJlcGVhdGVkQm9vbBgDIAMoCEICEAESKAoMYW5vdGhl",
            "ck1vbmV5GAIgASgLMhIuZ29vZ2xlLnR5cGUuTW9uZXkiWgoWQW5vdGhlclRv",
            "cExldmVsTWVzc2FnZRpACg5OZXN0ZWRNZXNzYWdlMhIuCgphVGltZXN0YW1w",
            "GAIgAygLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCodCgZBbkVudW0S",
            "CQoFQUxQSEEQABIICgRCRVRBEAEypgMKCEFTZXJ2aWNlEtQBCgRBUnBjEl4u",
            "Y29tLmFtYXpvbmF3cy5zZXJ2aWNlcy5zY2hlbWFyZWdpc3RyeS50ZXN0cy5w",
            "cm90b2J1Zi5zeW50YXgyLmFsbHR5cGVzLkFsbFR5cGVzLk5lc3RlZE1lc3Nh",
            "Z2UxGmwuY29tLmFtYXpvbmF3cy5zZXJ2aWNlcy5zY2hlbWFyZWdpc3RyeS50",
            "ZXN0cy5wcm90b2J1Zi5zeW50YXgyLmFsbHR5cGVzLkFub3RoZXJUb3BMZXZl",
            "bE1lc3NhZ2UuTmVzdGVkTWVzc2FnZTISwgEKDHN0cmVhbU1ldGhvZBJdLmNv",
            "bS5hbWF6b25hd3Muc2VydmljZXMuc2NoZW1hcmVnaXN0cnkudGVzdHMucHJv",
            "dG9idWYuc3ludGF4Mi5hbGx0eXBlcy5Bbm90aGVyVG9wTGV2ZWxNZXNzYWdl",
            "Gk8uY29tLmFtYXpvbmF3cy5zZXJ2aWNlcy5zY2hlbWFyZWdpc3RyeS50ZXN0",
            "cy5wcm90b2J1Zi5zeW50YXgyLmFsbHR5cGVzLkFsbFR5cGVzKAEwAUIRQg9B",
            "bGxUeXBlc1N5bnRheDI="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Google.Type.MoneyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnEnum), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AllTypes), global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AllTypes.Parser, new[]{ "StringType", "ByteType", "OneOfInt", "OneOfMoney", "RepeatedString", "RepeatedPackedInts", "Int64Bit1", "AnotherOneOfMoney", "OneOfBool", "OptionalSfixed32", "AnotherOptionalSfixed32", "OptionalSfixed64", "AnEnum2", "Uint64Type", "Int32Type", "Sint32Type", "Sint64Type", "Fixed32Type", "Fixed64Type", "NestedMessage1", "AComplexMap", "AnEnum1" }, new[]{ "AOneOf1", "AOneOf2" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AllTypes.Types.NestedMessage1), global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AllTypes.Types.NestedMessage1.Parser, new[]{ "FloatingType", "DoubleType" }, null, null, null, null),
            null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.TopLevelMessage), global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.TopLevelMessage.Parser, new[]{ "AnInt32", "RepeatedBool", "AnotherMoney" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnotherTopLevelMessage), global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnotherTopLevelMessage.Parser, null, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnotherTopLevelMessage.Types.NestedMessage2), global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnotherTopLevelMessage.Types.NestedMessage2.Parser, new[]{ "ATimestamp" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Enums
  public enum AnEnum {
    [pbr::OriginalName("ALPHA")] Alpha = 0,
    [pbr::OriginalName("BETA")] Beta = 1,
  }

  #endregion

  #region Messages
  /// <summary>
  ///0
  /// </summary>
  public sealed partial class AllTypes : pb::IMessage<AllTypes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AllTypes> _parser = new pb::MessageParser<AllTypes>(() => new AllTypes());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AllTypes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AllTypesSyntax2Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AllTypes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AllTypes(AllTypes other) : this() {
      _hasBits0 = other._hasBits0;
      stringType_ = other.stringType_;
      byteType_ = other.byteType_;
      repeatedString_ = other.repeatedString_.Clone();
      repeatedPackedInts_ = other.repeatedPackedInts_.Clone();
      optionalSfixed32_ = other.optionalSfixed32_;
      anotherOptionalSfixed32_ = other.anotherOptionalSfixed32_;
      optionalSfixed64_ = other.optionalSfixed64_;
      anEnum2_ = other.anEnum2_;
      uint64Type_ = other.uint64Type_;
      int32Type_ = other.int32Type_;
      sint32Type_ = other.sint32Type_;
      sint64Type_ = other.sint64Type_;
      fixed32Type_ = other.fixed32Type_;
      fixed64Type_ = other.fixed64Type_;
      nestedMessage1_ = other.nestedMessage1_ != null ? other.nestedMessage1_.Clone() : null;
      aComplexMap_ = other.aComplexMap_.Clone();
      anEnum1_ = other.anEnum1_;
      switch (other.AOneOf1Case) {
        case AOneOf1OneofCase.OneOfInt:
          OneOfInt = other.OneOfInt;
          break;
        case AOneOf1OneofCase.OneOfMoney:
          OneOfMoney = other.OneOfMoney.Clone();
          break;
      }

      switch (other.AOneOf2Case) {
        case AOneOf2OneofCase.Int64Bit1:
          Int64Bit1 = other.Int64Bit1;
          break;
        case AOneOf2OneofCase.AnotherOneOfMoney:
          AnotherOneOfMoney = other.AnotherOneOfMoney.Clone();
          break;
        case AOneOf2OneofCase.OneOfBool:
          OneOfBool = other.OneOfBool;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AllTypes Clone() {
      return new AllTypes(this);
    }

    /// <summary>Field number for the "stringType" field.</summary>
    public const int StringTypeFieldNumber = 80;
    private readonly static string StringTypeDefaultValue = "";

    private string stringType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StringType {
      get { return stringType_ ?? StringTypeDefaultValue; }
      set {
        stringType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "stringType" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStringType {
      get { return stringType_ != null; }
    }
    /// <summary>Clears the value of the "stringType" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStringType() {
      stringType_ = null;
    }

    /// <summary>Field number for the "byteType" field.</summary>
    public const int ByteTypeFieldNumber = 98;
    private readonly static pb::ByteString ByteTypeDefaultValue = pb::ByteString.Empty;

    private pb::ByteString byteType_;
    [global::System.ObsoleteAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ByteType {
      get { return byteType_ ?? ByteTypeDefaultValue; }
      set {
        byteType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "byteType" field is set</summary>
    [global::System.ObsoleteAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasByteType {
      get { return byteType_ != null; }
    }
    /// <summary>Clears the value of the "byteType" field</summary>
    [global::System.ObsoleteAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearByteType() {
      byteType_ = null;
    }

    /// <summary>Field number for the "oneOfInt" field.</summary>
    public const int OneOfIntFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OneOfInt {
      get { return HasOneOfInt ? (int) aOneOf1_ : 0; }
      set {
        aOneOf1_ = value;
        aOneOf1Case_ = AOneOf1OneofCase.OneOfInt;
      }
    }
    /// <summary>Gets whether the "oneOfInt" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOneOfInt {
      get { return aOneOf1Case_ == AOneOf1OneofCase.OneOfInt; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "oneOfInt" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneOfInt() {
      if (HasOneOfInt) {
        ClearAOneOf1();
      }
    }

    /// <summary>Field number for the "oneOfMoney" field.</summary>
    public const int OneOfMoneyFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.Money OneOfMoney {
      get { return aOneOf1Case_ == AOneOf1OneofCase.OneOfMoney ? (global::Google.Type.Money) aOneOf1_ : null; }
      set {
        aOneOf1_ = value;
        aOneOf1Case_ = value == null ? AOneOf1OneofCase.None : AOneOf1OneofCase.OneOfMoney;
      }
    }

    /// <summary>Field number for the "repeatedString" field.</summary>
    public const int RepeatedStringFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_repeatedString_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> repeatedString_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> RepeatedString {
      get { return repeatedString_; }
    }

    /// <summary>Field number for the "repeatedPackedInts" field.</summary>
    public const int RepeatedPackedIntsFieldNumber = 492;
    private static readonly pb::FieldCodec<string> _repeated_repeatedPackedInts_codec
        = pb::FieldCodec.ForString(3938);
    private readonly pbc::RepeatedField<string> repeatedPackedInts_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> RepeatedPackedInts {
      get { return repeatedPackedInts_; }
    }

    /// <summary>Field number for the "int64Bit1" field.</summary>
    public const int Int64Bit1FieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Int64Bit1 {
      get { return HasInt64Bit1 ? (long) aOneOf2_ : 0L; }
      set {
        aOneOf2_ = value;
        aOneOf2Case_ = AOneOf2OneofCase.Int64Bit1;
      }
    }
    /// <summary>Gets whether the "int64Bit1" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasInt64Bit1 {
      get { return aOneOf2Case_ == AOneOf2OneofCase.Int64Bit1; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "int64Bit1" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearInt64Bit1() {
      if (HasInt64Bit1) {
        ClearAOneOf2();
      }
    }

    /// <summary>Field number for the "anotherOneOfMoney" field.</summary>
    public const int AnotherOneOfMoneyFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.Money AnotherOneOfMoney {
      get { return aOneOf2Case_ == AOneOf2OneofCase.AnotherOneOfMoney ? (global::Google.Type.Money) aOneOf2_ : null; }
      set {
        aOneOf2_ = value;
        aOneOf2Case_ = value == null ? AOneOf2OneofCase.None : AOneOf2OneofCase.AnotherOneOfMoney;
      }
    }

    /// <summary>Field number for the "oneOfBool" field.</summary>
    public const int OneOfBoolFieldNumber = 239;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OneOfBool {
      get { return HasOneOfBool ? (bool) aOneOf2_ : false; }
      set {
        aOneOf2_ = value;
        aOneOf2Case_ = AOneOf2OneofCase.OneOfBool;
      }
    }
    /// <summary>Gets whether the "oneOfBool" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOneOfBool {
      get { return aOneOf2Case_ == AOneOf2OneofCase.OneOfBool; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "oneOfBool" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneOfBool() {
      if (HasOneOfBool) {
        ClearAOneOf2();
      }
    }

    /// <summary>Field number for the "optionalSfixed32" field.</summary>
    public const int OptionalSfixed32FieldNumber = 99;
    private readonly static int OptionalSfixed32DefaultValue = 0;

    private int optionalSfixed32_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OptionalSfixed32 {
      get { if ((_hasBits0 & 1) != 0) { return optionalSfixed32_; } else { return OptionalSfixed32DefaultValue; } }
      set {
        _hasBits0 |= 1;
        optionalSfixed32_ = value;
      }
    }
    /// <summary>Gets whether the "optionalSfixed32" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOptionalSfixed32 {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "optionalSfixed32" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOptionalSfixed32() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "anotherOptionalSfixed32" field.</summary>
    public const int AnotherOptionalSfixed32FieldNumber = 992;
    private readonly static int AnotherOptionalSfixed32DefaultValue = 0;

    private int anotherOptionalSfixed32_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AnotherOptionalSfixed32 {
      get { if ((_hasBits0 & 4) != 0) { return anotherOptionalSfixed32_; } else { return AnotherOptionalSfixed32DefaultValue; } }
      set {
        _hasBits0 |= 4;
        anotherOptionalSfixed32_ = value;
      }
    }
    /// <summary>Gets whether the "anotherOptionalSfixed32" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAnotherOptionalSfixed32 {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "anotherOptionalSfixed32" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAnotherOptionalSfixed32() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "optionalSfixed64" field.</summary>
    public const int OptionalSfixed64FieldNumber = 991;
    private readonly static long OptionalSfixed64DefaultValue = 0L;

    private long optionalSfixed64_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long OptionalSfixed64 {
      get { if ((_hasBits0 & 2) != 0) { return optionalSfixed64_; } else { return OptionalSfixed64DefaultValue; } }
      set {
        _hasBits0 |= 2;
        optionalSfixed64_ = value;
      }
    }
    /// <summary>Gets whether the "optionalSfixed64" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOptionalSfixed64 {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "optionalSfixed64" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOptionalSfixed64() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "anEnum2" field.</summary>
    public const int AnEnum2FieldNumber = 1902;
    private readonly static global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnEnum AnEnum2DefaultValue = global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnEnum.Alpha;

    private global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnEnum anEnum2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnEnum AnEnum2 {
      get { if ((_hasBits0 & 512) != 0) { return anEnum2_; } else { return AnEnum2DefaultValue; } }
      set {
        _hasBits0 |= 512;
        anEnum2_ = value;
      }
    }
    /// <summary>Gets whether the "anEnum2" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAnEnum2 {
      get { return (_hasBits0 & 512) != 0; }
    }
    /// <summary>Clears the value of the "anEnum2" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAnEnum2() {
      _hasBits0 &= ~512;
    }

    /// <summary>Field number for the "uint64Type" field.</summary>
    public const int Uint64TypeFieldNumber = 993;
    private readonly static ulong Uint64TypeDefaultValue = 0UL;

    private ulong uint64Type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Uint64Type {
      get { if ((_hasBits0 & 8) != 0) { return uint64Type_; } else { return Uint64TypeDefaultValue; } }
      set {
        _hasBits0 |= 8;
        uint64Type_ = value;
      }
    }
    /// <summary>Gets whether the "uint64Type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUint64Type {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "uint64Type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUint64Type() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "int32Type" field.</summary>
    public const int Int32TypeFieldNumber = 994;
    private readonly static uint Int32TypeDefaultValue = 0;

    private uint int32Type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Int32Type {
      get { if ((_hasBits0 & 16) != 0) { return int32Type_; } else { return Int32TypeDefaultValue; } }
      set {
        _hasBits0 |= 16;
        int32Type_ = value;
      }
    }
    /// <summary>Gets whether the "int32Type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasInt32Type {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "int32Type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearInt32Type() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "sint32Type" field.</summary>
    public const int Sint32TypeFieldNumber = 995;
    private readonly static int Sint32TypeDefaultValue = 0;

    private int sint32Type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Sint32Type {
      get { if ((_hasBits0 & 32) != 0) { return sint32Type_; } else { return Sint32TypeDefaultValue; } }
      set {
        _hasBits0 |= 32;
        sint32Type_ = value;
      }
    }
    /// <summary>Gets whether the "sint32Type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSint32Type {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "sint32Type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSint32Type() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "sint64Type" field.</summary>
    public const int Sint64TypeFieldNumber = 996;
    private readonly static long Sint64TypeDefaultValue = 0L;

    private long sint64Type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Sint64Type {
      get { if ((_hasBits0 & 64) != 0) { return sint64Type_; } else { return Sint64TypeDefaultValue; } }
      set {
        _hasBits0 |= 64;
        sint64Type_ = value;
      }
    }
    /// <summary>Gets whether the "sint64Type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSint64Type {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "sint64Type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSint64Type() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "fixed32Type" field.</summary>
    public const int Fixed32TypeFieldNumber = 997;
    private readonly static uint Fixed32TypeDefaultValue = 0;

    private uint fixed32Type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Fixed32Type {
      get { if ((_hasBits0 & 128) != 0) { return fixed32Type_; } else { return Fixed32TypeDefaultValue; } }
      set {
        _hasBits0 |= 128;
        fixed32Type_ = value;
      }
    }
    /// <summary>Gets whether the "fixed32Type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFixed32Type {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "fixed32Type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFixed32Type() {
      _hasBits0 &= ~128;
    }

    /// <summary>Field number for the "fixed64Type" field.</summary>
    public const int Fixed64TypeFieldNumber = 998;
    private readonly static ulong Fixed64TypeDefaultValue = 0UL;

    private ulong fixed64Type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Fixed64Type {
      get { if ((_hasBits0 & 256) != 0) { return fixed64Type_; } else { return Fixed64TypeDefaultValue; } }
      set {
        _hasBits0 |= 256;
        fixed64Type_ = value;
      }
    }
    /// <summary>Gets whether the "fixed64Type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFixed64Type {
      get { return (_hasBits0 & 256) != 0; }
    }
    /// <summary>Clears the value of the "fixed64Type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFixed64Type() {
      _hasBits0 &= ~256;
    }

    /// <summary>Field number for the "nestedMessage1" field.</summary>
    public const int NestedMessage1FieldNumber = 198;
    private global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AllTypes.Types.NestedMessage1 nestedMessage1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AllTypes.Types.NestedMessage1 NestedMessage1 {
      get { return nestedMessage1_; }
      set {
        nestedMessage1_ = value;
      }
    }

    /// <summary>Field number for the "aComplexMap" field.</summary>
    public const int AComplexMapFieldNumber = 2394;
    private static readonly pbc::MapField<int, global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnotherTopLevelMessage.Types.NestedMessage2>.Codec _map_aComplexMap_codec
        = new pbc::MapField<int, global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnotherTopLevelMessage.Types.NestedMessage2>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnotherTopLevelMessage.Types.NestedMessage2.Parser), 19154);
    private readonly pbc::MapField<int, global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnotherTopLevelMessage.Types.NestedMessage2> aComplexMap_ = new pbc::MapField<int, global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnotherTopLevelMessage.Types.NestedMessage2>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnotherTopLevelMessage.Types.NestedMessage2> AComplexMap {
      get { return aComplexMap_; }
    }

    /// <summary>Field number for the "anEnum1" field.</summary>
    public const int AnEnum1FieldNumber = 1999;
    private readonly static global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnEnum AnEnum1DefaultValue = global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnEnum.Alpha;

    private global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnEnum anEnum1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnEnum AnEnum1 {
      get { if ((_hasBits0 & 1024) != 0) { return anEnum1_; } else { return AnEnum1DefaultValue; } }
      set {
        _hasBits0 |= 1024;
        anEnum1_ = value;
      }
    }
    /// <summary>Gets whether the "anEnum1" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAnEnum1 {
      get { return (_hasBits0 & 1024) != 0; }
    }
    /// <summary>Clears the value of the "anEnum1" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAnEnum1() {
      _hasBits0 &= ~1024;
    }

    private object aOneOf1_;
    /// <summary>Enum of possible cases for the "aOneOf1" oneof.</summary>
    public enum AOneOf1OneofCase {
      None = 0,
      OneOfInt = 1,
      OneOfMoney = 3,
    }
    private AOneOf1OneofCase aOneOf1Case_ = AOneOf1OneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AOneOf1OneofCase AOneOf1Case {
      get { return aOneOf1Case_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAOneOf1() {
      aOneOf1Case_ = AOneOf1OneofCase.None;
      aOneOf1_ = null;
    }

    private object aOneOf2_;
    /// <summary>Enum of possible cases for the "aOneOf2" oneof.</summary>
    public enum AOneOf2OneofCase {
      None = 0,
      Int64Bit1 = 5,
      AnotherOneOfMoney = 6,
      OneOfBool = 239,
    }
    private AOneOf2OneofCase aOneOf2Case_ = AOneOf2OneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AOneOf2OneofCase AOneOf2Case {
      get { return aOneOf2Case_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAOneOf2() {
      aOneOf2Case_ = AOneOf2OneofCase.None;
      aOneOf2_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AllTypes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AllTypes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StringType != other.StringType) return false;
      if (ByteType != other.ByteType) return false;
      if (OneOfInt != other.OneOfInt) return false;
      if (!object.Equals(OneOfMoney, other.OneOfMoney)) return false;
      if(!repeatedString_.Equals(other.repeatedString_)) return false;
      if(!repeatedPackedInts_.Equals(other.repeatedPackedInts_)) return false;
      if (Int64Bit1 != other.Int64Bit1) return false;
      if (!object.Equals(AnotherOneOfMoney, other.AnotherOneOfMoney)) return false;
      if (OneOfBool != other.OneOfBool) return false;
      if (OptionalSfixed32 != other.OptionalSfixed32) return false;
      if (AnotherOptionalSfixed32 != other.AnotherOptionalSfixed32) return false;
      if (OptionalSfixed64 != other.OptionalSfixed64) return false;
      if (AnEnum2 != other.AnEnum2) return false;
      if (Uint64Type != other.Uint64Type) return false;
      if (Int32Type != other.Int32Type) return false;
      if (Sint32Type != other.Sint32Type) return false;
      if (Sint64Type != other.Sint64Type) return false;
      if (Fixed32Type != other.Fixed32Type) return false;
      if (Fixed64Type != other.Fixed64Type) return false;
      if (!object.Equals(NestedMessage1, other.NestedMessage1)) return false;
      if (!AComplexMap.Equals(other.AComplexMap)) return false;
      if (AnEnum1 != other.AnEnum1) return false;
      if (AOneOf1Case != other.AOneOf1Case) return false;
      if (AOneOf2Case != other.AOneOf2Case) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasStringType) hash ^= StringType.GetHashCode();
      if (HasByteType) hash ^= ByteType.GetHashCode();
      if (HasOneOfInt) hash ^= OneOfInt.GetHashCode();
      if (aOneOf1Case_ == AOneOf1OneofCase.OneOfMoney) hash ^= OneOfMoney.GetHashCode();
      hash ^= repeatedString_.GetHashCode();
      hash ^= repeatedPackedInts_.GetHashCode();
      if (HasInt64Bit1) hash ^= Int64Bit1.GetHashCode();
      if (aOneOf2Case_ == AOneOf2OneofCase.AnotherOneOfMoney) hash ^= AnotherOneOfMoney.GetHashCode();
      if (HasOneOfBool) hash ^= OneOfBool.GetHashCode();
      if (HasOptionalSfixed32) hash ^= OptionalSfixed32.GetHashCode();
      if (HasAnotherOptionalSfixed32) hash ^= AnotherOptionalSfixed32.GetHashCode();
      if (HasOptionalSfixed64) hash ^= OptionalSfixed64.GetHashCode();
      if (HasAnEnum2) hash ^= AnEnum2.GetHashCode();
      if (HasUint64Type) hash ^= Uint64Type.GetHashCode();
      if (HasInt32Type) hash ^= Int32Type.GetHashCode();
      if (HasSint32Type) hash ^= Sint32Type.GetHashCode();
      if (HasSint64Type) hash ^= Sint64Type.GetHashCode();
      if (HasFixed32Type) hash ^= Fixed32Type.GetHashCode();
      if (HasFixed64Type) hash ^= Fixed64Type.GetHashCode();
      if (nestedMessage1_ != null) hash ^= NestedMessage1.GetHashCode();
      hash ^= AComplexMap.GetHashCode();
      if (HasAnEnum1) hash ^= AnEnum1.GetHashCode();
      hash ^= (int) aOneOf1Case_;
      hash ^= (int) aOneOf2Case_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasOneOfInt) {
        output.WriteRawTag(8);
        output.WriteInt32(OneOfInt);
      }
      if (aOneOf1Case_ == AOneOf1OneofCase.OneOfMoney) {
        output.WriteRawTag(26);
        output.WriteMessage(OneOfMoney);
      }
      repeatedString_.WriteTo(output, _repeated_repeatedString_codec);
      if (HasInt64Bit1) {
        output.WriteRawTag(40);
        output.WriteInt64(Int64Bit1);
      }
      if (aOneOf2Case_ == AOneOf2OneofCase.AnotherOneOfMoney) {
        output.WriteRawTag(50);
        output.WriteMessage(AnotherOneOfMoney);
      }
      if (HasStringType) {
        output.WriteRawTag(130, 5);
        output.WriteString(StringType);
      }
      if (HasByteType) {
        output.WriteRawTag(146, 6);
        output.WriteBytes(ByteType);
      }
      if (HasOptionalSfixed32) {
        output.WriteRawTag(157, 6);
        output.WriteSFixed32(OptionalSfixed32);
      }
      if (nestedMessage1_ != null) {
        output.WriteRawTag(178, 12);
        output.WriteMessage(NestedMessage1);
      }
      if (HasOneOfBool) {
        output.WriteRawTag(248, 14);
        output.WriteBool(OneOfBool);
      }
      repeatedPackedInts_.WriteTo(output, _repeated_repeatedPackedInts_codec);
      if (HasOptionalSfixed64) {
        output.WriteRawTag(249, 61);
        output.WriteSFixed64(OptionalSfixed64);
      }
      if (HasAnotherOptionalSfixed32) {
        output.WriteRawTag(133, 62);
        output.WriteSFixed32(AnotherOptionalSfixed32);
      }
      if (HasUint64Type) {
        output.WriteRawTag(136, 62);
        output.WriteUInt64(Uint64Type);
      }
      if (HasInt32Type) {
        output.WriteRawTag(144, 62);
        output.WriteUInt32(Int32Type);
      }
      if (HasSint32Type) {
        output.WriteRawTag(152, 62);
        output.WriteSInt32(Sint32Type);
      }
      if (HasSint64Type) {
        output.WriteRawTag(160, 62);
        output.WriteSInt64(Sint64Type);
      }
      if (HasFixed32Type) {
        output.WriteRawTag(173, 62);
        output.WriteFixed32(Fixed32Type);
      }
      if (HasFixed64Type) {
        output.WriteRawTag(177, 62);
        output.WriteFixed64(Fixed64Type);
      }
      if (HasAnEnum2) {
        output.WriteRawTag(240, 118);
        output.WriteEnum((int) AnEnum2);
      }
      if (HasAnEnum1) {
        output.WriteRawTag(248, 124);
        output.WriteEnum((int) AnEnum1);
      }
      aComplexMap_.WriteTo(output, _map_aComplexMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasOneOfInt) {
        output.WriteRawTag(8);
        output.WriteInt32(OneOfInt);
      }
      if (aOneOf1Case_ == AOneOf1OneofCase.OneOfMoney) {
        output.WriteRawTag(26);
        output.WriteMessage(OneOfMoney);
      }
      repeatedString_.WriteTo(ref output, _repeated_repeatedString_codec);
      if (HasInt64Bit1) {
        output.WriteRawTag(40);
        output.WriteInt64(Int64Bit1);
      }
      if (aOneOf2Case_ == AOneOf2OneofCase.AnotherOneOfMoney) {
        output.WriteRawTag(50);
        output.WriteMessage(AnotherOneOfMoney);
      }
      if (HasStringType) {
        output.WriteRawTag(130, 5);
        output.WriteString(StringType);
      }
      if (HasByteType) {
        output.WriteRawTag(146, 6);
        output.WriteBytes(ByteType);
      }
      if (HasOptionalSfixed32) {
        output.WriteRawTag(157, 6);
        output.WriteSFixed32(OptionalSfixed32);
      }
      if (nestedMessage1_ != null) {
        output.WriteRawTag(178, 12);
        output.WriteMessage(NestedMessage1);
      }
      if (HasOneOfBool) {
        output.WriteRawTag(248, 14);
        output.WriteBool(OneOfBool);
      }
      repeatedPackedInts_.WriteTo(ref output, _repeated_repeatedPackedInts_codec);
      if (HasOptionalSfixed64) {
        output.WriteRawTag(249, 61);
        output.WriteSFixed64(OptionalSfixed64);
      }
      if (HasAnotherOptionalSfixed32) {
        output.WriteRawTag(133, 62);
        output.WriteSFixed32(AnotherOptionalSfixed32);
      }
      if (HasUint64Type) {
        output.WriteRawTag(136, 62);
        output.WriteUInt64(Uint64Type);
      }
      if (HasInt32Type) {
        output.WriteRawTag(144, 62);
        output.WriteUInt32(Int32Type);
      }
      if (HasSint32Type) {
        output.WriteRawTag(152, 62);
        output.WriteSInt32(Sint32Type);
      }
      if (HasSint64Type) {
        output.WriteRawTag(160, 62);
        output.WriteSInt64(Sint64Type);
      }
      if (HasFixed32Type) {
        output.WriteRawTag(173, 62);
        output.WriteFixed32(Fixed32Type);
      }
      if (HasFixed64Type) {
        output.WriteRawTag(177, 62);
        output.WriteFixed64(Fixed64Type);
      }
      if (HasAnEnum2) {
        output.WriteRawTag(240, 118);
        output.WriteEnum((int) AnEnum2);
      }
      if (HasAnEnum1) {
        output.WriteRawTag(248, 124);
        output.WriteEnum((int) AnEnum1);
      }
      aComplexMap_.WriteTo(ref output, _map_aComplexMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasStringType) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(StringType);
      }
      if (HasByteType) {
        size += 2 + pb::CodedOutputStream.ComputeBytesSize(ByteType);
      }
      if (HasOneOfInt) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OneOfInt);
      }
      if (aOneOf1Case_ == AOneOf1OneofCase.OneOfMoney) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OneOfMoney);
      }
      size += repeatedString_.CalculateSize(_repeated_repeatedString_codec);
      size += repeatedPackedInts_.CalculateSize(_repeated_repeatedPackedInts_codec);
      if (HasInt64Bit1) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Int64Bit1);
      }
      if (aOneOf2Case_ == AOneOf2OneofCase.AnotherOneOfMoney) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AnotherOneOfMoney);
      }
      if (HasOneOfBool) {
        size += 2 + 1;
      }
      if (HasOptionalSfixed32) {
        size += 2 + 4;
      }
      if (HasAnotherOptionalSfixed32) {
        size += 2 + 4;
      }
      if (HasOptionalSfixed64) {
        size += 2 + 8;
      }
      if (HasAnEnum2) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) AnEnum2);
      }
      if (HasUint64Type) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(Uint64Type);
      }
      if (HasInt32Type) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Int32Type);
      }
      if (HasSint32Type) {
        size += 2 + pb::CodedOutputStream.ComputeSInt32Size(Sint32Type);
      }
      if (HasSint64Type) {
        size += 2 + pb::CodedOutputStream.ComputeSInt64Size(Sint64Type);
      }
      if (HasFixed32Type) {
        size += 2 + 4;
      }
      if (HasFixed64Type) {
        size += 2 + 8;
      }
      if (nestedMessage1_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(NestedMessage1);
      }
      size += aComplexMap_.CalculateSize(_map_aComplexMap_codec);
      if (HasAnEnum1) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) AnEnum1);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AllTypes other) {
      if (other == null) {
        return;
      }
      if (other.HasStringType) {
        StringType = other.StringType;
      }
      if (other.HasByteType) {
        ByteType = other.ByteType;
      }
      repeatedString_.Add(other.repeatedString_);
      repeatedPackedInts_.Add(other.repeatedPackedInts_);
      if (other.HasOptionalSfixed32) {
        OptionalSfixed32 = other.OptionalSfixed32;
      }
      if (other.HasAnotherOptionalSfixed32) {
        AnotherOptionalSfixed32 = other.AnotherOptionalSfixed32;
      }
      if (other.HasOptionalSfixed64) {
        OptionalSfixed64 = other.OptionalSfixed64;
      }
      if (other.HasAnEnum2) {
        AnEnum2 = other.AnEnum2;
      }
      if (other.HasUint64Type) {
        Uint64Type = other.Uint64Type;
      }
      if (other.HasInt32Type) {
        Int32Type = other.Int32Type;
      }
      if (other.HasSint32Type) {
        Sint32Type = other.Sint32Type;
      }
      if (other.HasSint64Type) {
        Sint64Type = other.Sint64Type;
      }
      if (other.HasFixed32Type) {
        Fixed32Type = other.Fixed32Type;
      }
      if (other.HasFixed64Type) {
        Fixed64Type = other.Fixed64Type;
      }
      if (other.nestedMessage1_ != null) {
        if (nestedMessage1_ == null) {
          NestedMessage1 = new global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AllTypes.Types.NestedMessage1();
        }
        NestedMessage1.MergeFrom(other.NestedMessage1);
      }
      aComplexMap_.Add(other.aComplexMap_);
      if (other.HasAnEnum1) {
        AnEnum1 = other.AnEnum1;
      }
      switch (other.AOneOf1Case) {
        case AOneOf1OneofCase.OneOfInt:
          OneOfInt = other.OneOfInt;
          break;
        case AOneOf1OneofCase.OneOfMoney:
          if (OneOfMoney == null) {
            OneOfMoney = new global::Google.Type.Money();
          }
          OneOfMoney.MergeFrom(other.OneOfMoney);
          break;
      }

      switch (other.AOneOf2Case) {
        case AOneOf2OneofCase.Int64Bit1:
          Int64Bit1 = other.Int64Bit1;
          break;
        case AOneOf2OneofCase.AnotherOneOfMoney:
          if (AnotherOneOfMoney == null) {
            AnotherOneOfMoney = new global::Google.Type.Money();
          }
          AnotherOneOfMoney.MergeFrom(other.AnotherOneOfMoney);
          break;
        case AOneOf2OneofCase.OneOfBool:
          OneOfBool = other.OneOfBool;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OneOfInt = input.ReadInt32();
            break;
          }
          case 26: {
            global::Google.Type.Money subBuilder = new global::Google.Type.Money();
            if (aOneOf1Case_ == AOneOf1OneofCase.OneOfMoney) {
              subBuilder.MergeFrom(OneOfMoney);
            }
            input.ReadMessage(subBuilder);
            OneOfMoney = subBuilder;
            break;
          }
          case 34: {
            repeatedString_.AddEntriesFrom(input, _repeated_repeatedString_codec);
            break;
          }
          case 40: {
            Int64Bit1 = input.ReadInt64();
            break;
          }
          case 50: {
            global::Google.Type.Money subBuilder = new global::Google.Type.Money();
            if (aOneOf2Case_ == AOneOf2OneofCase.AnotherOneOfMoney) {
              subBuilder.MergeFrom(AnotherOneOfMoney);
            }
            input.ReadMessage(subBuilder);
            AnotherOneOfMoney = subBuilder;
            break;
          }
          case 642: {
            StringType = input.ReadString();
            break;
          }
          case 786: {
            ByteType = input.ReadBytes();
            break;
          }
          case 797: {
            OptionalSfixed32 = input.ReadSFixed32();
            break;
          }
          case 1586: {
            if (nestedMessage1_ == null) {
              NestedMessage1 = new global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AllTypes.Types.NestedMessage1();
            }
            input.ReadMessage(NestedMessage1);
            break;
          }
          case 1912: {
            OneOfBool = input.ReadBool();
            break;
          }
          case 3938: {
            repeatedPackedInts_.AddEntriesFrom(input, _repeated_repeatedPackedInts_codec);
            break;
          }
          case 7929: {
            OptionalSfixed64 = input.ReadSFixed64();
            break;
          }
          case 7941: {
            AnotherOptionalSfixed32 = input.ReadSFixed32();
            break;
          }
          case 7944: {
            Uint64Type = input.ReadUInt64();
            break;
          }
          case 7952: {
            Int32Type = input.ReadUInt32();
            break;
          }
          case 7960: {
            Sint32Type = input.ReadSInt32();
            break;
          }
          case 7968: {
            Sint64Type = input.ReadSInt64();
            break;
          }
          case 7981: {
            Fixed32Type = input.ReadFixed32();
            break;
          }
          case 7985: {
            Fixed64Type = input.ReadFixed64();
            break;
          }
          case 15216: {
            AnEnum2 = (global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnEnum) input.ReadEnum();
            break;
          }
          case 15992: {
            AnEnum1 = (global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnEnum) input.ReadEnum();
            break;
          }
          case 19154: {
            aComplexMap_.AddEntriesFrom(input, _map_aComplexMap_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OneOfInt = input.ReadInt32();
            break;
          }
          case 26: {
            global::Google.Type.Money subBuilder = new global::Google.Type.Money();
            if (aOneOf1Case_ == AOneOf1OneofCase.OneOfMoney) {
              subBuilder.MergeFrom(OneOfMoney);
            }
            input.ReadMessage(subBuilder);
            OneOfMoney = subBuilder;
            break;
          }
          case 34: {
            repeatedString_.AddEntriesFrom(ref input, _repeated_repeatedString_codec);
            break;
          }
          case 40: {
            Int64Bit1 = input.ReadInt64();
            break;
          }
          case 50: {
            global::Google.Type.Money subBuilder = new global::Google.Type.Money();
            if (aOneOf2Case_ == AOneOf2OneofCase.AnotherOneOfMoney) {
              subBuilder.MergeFrom(AnotherOneOfMoney);
            }
            input.ReadMessage(subBuilder);
            AnotherOneOfMoney = subBuilder;
            break;
          }
          case 642: {
            StringType = input.ReadString();
            break;
          }
          case 786: {
            ByteType = input.ReadBytes();
            break;
          }
          case 797: {
            OptionalSfixed32 = input.ReadSFixed32();
            break;
          }
          case 1586: {
            if (nestedMessage1_ == null) {
              NestedMessage1 = new global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AllTypes.Types.NestedMessage1();
            }
            input.ReadMessage(NestedMessage1);
            break;
          }
          case 1912: {
            OneOfBool = input.ReadBool();
            break;
          }
          case 3938: {
            repeatedPackedInts_.AddEntriesFrom(ref input, _repeated_repeatedPackedInts_codec);
            break;
          }
          case 7929: {
            OptionalSfixed64 = input.ReadSFixed64();
            break;
          }
          case 7941: {
            AnotherOptionalSfixed32 = input.ReadSFixed32();
            break;
          }
          case 7944: {
            Uint64Type = input.ReadUInt64();
            break;
          }
          case 7952: {
            Int32Type = input.ReadUInt32();
            break;
          }
          case 7960: {
            Sint32Type = input.ReadSInt32();
            break;
          }
          case 7968: {
            Sint64Type = input.ReadSInt64();
            break;
          }
          case 7981: {
            Fixed32Type = input.ReadFixed32();
            break;
          }
          case 7985: {
            Fixed64Type = input.ReadFixed64();
            break;
          }
          case 15216: {
            AnEnum2 = (global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnEnum) input.ReadEnum();
            break;
          }
          case 15992: {
            AnEnum1 = (global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnEnum) input.ReadEnum();
            break;
          }
          case 19154: {
            aComplexMap_.AddEntriesFrom(ref input, _map_aComplexMap_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AllTypes message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class NestedMessage1 : pb::IMessage<NestedMessage1>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<NestedMessage1> _parser = new pb::MessageParser<NestedMessage1>(() => new NestedMessage1());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<NestedMessage1> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AllTypes.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public NestedMessage1() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public NestedMessage1(NestedMessage1 other) : this() {
          _hasBits0 = other._hasBits0;
          floatingType_ = other.floatingType_;
          doubleType_ = other.doubleType_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public NestedMessage1 Clone() {
          return new NestedMessage1(this);
        }

        /// <summary>Field number for the "floatingType" field.</summary>
        public const int FloatingTypeFieldNumber = 100;
        private readonly static float FloatingTypeDefaultValue = 0F;

        private float floatingType_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float FloatingType {
          get { if ((_hasBits0 & 1) != 0) { return floatingType_; } else { return FloatingTypeDefaultValue; } }
          set {
            _hasBits0 |= 1;
            floatingType_ = value;
          }
        }
        /// <summary>Gets whether the "floatingType" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasFloatingType {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "floatingType" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearFloatingType() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "doubleType" field.</summary>
        public const int DoubleTypeFieldNumber = 101;
        private readonly static double DoubleTypeDefaultValue = 0D;

        private double doubleType_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double DoubleType {
          get { if ((_hasBits0 & 2) != 0) { return doubleType_; } else { return DoubleTypeDefaultValue; } }
          set {
            _hasBits0 |= 2;
            doubleType_ = value;
          }
        }
        /// <summary>Gets whether the "doubleType" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasDoubleType {
          get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "doubleType" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearDoubleType() {
          _hasBits0 &= ~2;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as NestedMessage1);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(NestedMessage1 other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FloatingType, other.FloatingType)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DoubleType, other.DoubleType)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasFloatingType) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FloatingType);
          if (HasDoubleType) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DoubleType);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasFloatingType) {
            output.WriteRawTag(165, 6);
            output.WriteFloat(FloatingType);
          }
          if (HasDoubleType) {
            output.WriteRawTag(169, 6);
            output.WriteDouble(DoubleType);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasFloatingType) {
            output.WriteRawTag(165, 6);
            output.WriteFloat(FloatingType);
          }
          if (HasDoubleType) {
            output.WriteRawTag(169, 6);
            output.WriteDouble(DoubleType);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasFloatingType) {
            size += 2 + 4;
          }
          if (HasDoubleType) {
            size += 2 + 8;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(NestedMessage1 other) {
          if (other == null) {
            return;
          }
          if (other.HasFloatingType) {
            FloatingType = other.FloatingType;
          }
          if (other.HasDoubleType) {
            DoubleType = other.DoubleType;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 805: {
                FloatingType = input.ReadFloat();
                break;
              }
              case 809: {
                DoubleType = input.ReadDouble();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 805: {
                FloatingType = input.ReadFloat();
                break;
              }
              case 809: {
                DoubleType = input.ReadDouble();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  public sealed partial class TopLevelMessage : pb::IMessage<TopLevelMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TopLevelMessage> _parser = new pb::MessageParser<TopLevelMessage>(() => new TopLevelMessage());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TopLevelMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AllTypesSyntax2Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TopLevelMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TopLevelMessage(TopLevelMessage other) : this() {
      _hasBits0 = other._hasBits0;
      anInt32_ = other.anInt32_;
      repeatedBool_ = other.repeatedBool_.Clone();
      anotherMoney_ = other.anotherMoney_ != null ? other.anotherMoney_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TopLevelMessage Clone() {
      return new TopLevelMessage(this);
    }

    /// <summary>Field number for the "anInt32" field.</summary>
    public const int AnInt32FieldNumber = 1;
    private readonly static int AnInt32DefaultValue = 0;

    private int anInt32_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AnInt32 {
      get { if ((_hasBits0 & 1) != 0) { return anInt32_; } else { return AnInt32DefaultValue; } }
      set {
        _hasBits0 |= 1;
        anInt32_ = value;
      }
    }
    /// <summary>Gets whether the "anInt32" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAnInt32 {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "anInt32" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAnInt32() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "repeatedBool" field.</summary>
    public const int RepeatedBoolFieldNumber = 3;
    private static readonly pb::FieldCodec<bool> _repeated_repeatedBool_codec
        = pb::FieldCodec.ForBool(26);
    private readonly pbc::RepeatedField<bool> repeatedBool_ = new pbc::RepeatedField<bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<bool> RepeatedBool {
      get { return repeatedBool_; }
    }

    /// <summary>Field number for the "anotherMoney" field.</summary>
    public const int AnotherMoneyFieldNumber = 2;
    private global::Google.Type.Money anotherMoney_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.Money AnotherMoney {
      get { return anotherMoney_; }
      set {
        anotherMoney_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TopLevelMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TopLevelMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AnInt32 != other.AnInt32) return false;
      if(!repeatedBool_.Equals(other.repeatedBool_)) return false;
      if (!object.Equals(AnotherMoney, other.AnotherMoney)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasAnInt32) hash ^= AnInt32.GetHashCode();
      hash ^= repeatedBool_.GetHashCode();
      if (anotherMoney_ != null) hash ^= AnotherMoney.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasAnInt32) {
        output.WriteRawTag(8);
        output.WriteInt32(AnInt32);
      }
      if (anotherMoney_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AnotherMoney);
      }
      repeatedBool_.WriteTo(output, _repeated_repeatedBool_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasAnInt32) {
        output.WriteRawTag(8);
        output.WriteInt32(AnInt32);
      }
      if (anotherMoney_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AnotherMoney);
      }
      repeatedBool_.WriteTo(ref output, _repeated_repeatedBool_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasAnInt32) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AnInt32);
      }
      size += repeatedBool_.CalculateSize(_repeated_repeatedBool_codec);
      if (anotherMoney_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AnotherMoney);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TopLevelMessage other) {
      if (other == null) {
        return;
      }
      if (other.HasAnInt32) {
        AnInt32 = other.AnInt32;
      }
      repeatedBool_.Add(other.repeatedBool_);
      if (other.anotherMoney_ != null) {
        if (anotherMoney_ == null) {
          AnotherMoney = new global::Google.Type.Money();
        }
        AnotherMoney.MergeFrom(other.AnotherMoney);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AnInt32 = input.ReadInt32();
            break;
          }
          case 18: {
            if (anotherMoney_ == null) {
              AnotherMoney = new global::Google.Type.Money();
            }
            input.ReadMessage(AnotherMoney);
            break;
          }
          case 26:
          case 24: {
            repeatedBool_.AddEntriesFrom(input, _repeated_repeatedBool_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AnInt32 = input.ReadInt32();
            break;
          }
          case 18: {
            if (anotherMoney_ == null) {
              AnotherMoney = new global::Google.Type.Money();
            }
            input.ReadMessage(AnotherMoney);
            break;
          }
          case 26:
          case 24: {
            repeatedBool_.AddEntriesFrom(ref input, _repeated_repeatedBool_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///a comment
  /// </summary>
  public sealed partial class AnotherTopLevelMessage : pb::IMessage<AnotherTopLevelMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AnotherTopLevelMessage> _parser = new pb::MessageParser<AnotherTopLevelMessage>(() => new AnotherTopLevelMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AnotherTopLevelMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AllTypesSyntax2Reflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnotherTopLevelMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnotherTopLevelMessage(AnotherTopLevelMessage other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnotherTopLevelMessage Clone() {
      return new AnotherTopLevelMessage(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AnotherTopLevelMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AnotherTopLevelMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AnotherTopLevelMessage other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AnotherTopLevelMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class NestedMessage2 : pb::IMessage<NestedMessage2>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<NestedMessage2> _parser = new pb::MessageParser<NestedMessage2>(() => new NestedMessage2());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<NestedMessage2> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Com.Amazonaws.Services.Schemaregistry.Tests.Protobuf.Syntax2.Alltypes.AnotherTopLevelMessage.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public NestedMessage2() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public NestedMessage2(NestedMessage2 other) : this() {
          aTimestamp_ = other.aTimestamp_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public NestedMessage2 Clone() {
          return new NestedMessage2(this);
        }

        /// <summary>Field number for the "aTimestamp" field.</summary>
        public const int ATimestampFieldNumber = 2;
        private static readonly pb::FieldCodec<global::Google.Protobuf.WellKnownTypes.Timestamp> _repeated_aTimestamp_codec
            = pb::FieldCodec.ForMessage(18, global::Google.Protobuf.WellKnownTypes.Timestamp.Parser);
        private readonly pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Timestamp> aTimestamp_ = new pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Timestamp>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Timestamp> ATimestamp {
          get { return aTimestamp_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as NestedMessage2);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(NestedMessage2 other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if(!aTimestamp_.Equals(other.aTimestamp_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          hash ^= aTimestamp_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          aTimestamp_.WriteTo(output, _repeated_aTimestamp_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          aTimestamp_.WriteTo(ref output, _repeated_aTimestamp_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          size += aTimestamp_.CalculateSize(_repeated_aTimestamp_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(NestedMessage2 other) {
          if (other == null) {
            return;
          }
          aTimestamp_.Add(other.aTimestamp_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 18: {
                aTimestamp_.AddEntriesFrom(input, _repeated_aTimestamp_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 18: {
                aTimestamp_.AddEntriesFrom(ref input, _repeated_aTimestamp_codec);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
