// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TestSyntax2JavaPackage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from TestSyntax2JavaPackage.proto</summary>
public static partial class TestSyntax2JavaPackageReflection {

  #region Descriptor
  /// <summary>File descriptor for TestSyntax2JavaPackage.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static TestSyntax2JavaPackageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChxUZXN0U3ludGF4MkphdmFQYWNrYWdlLnByb3RvGhdnb29nbGUvdHlwZS9t",
          "b25leS5wcm90byI+CgNGb28SCQoBYRgBIAIoBRIJCgFiGAIgASgJEiEKBW1v",
          "bmV5GAUgAigLMhIuZ29vZ2xlLnR5cGUuTW9uZXlCPgo8Y29tLmFtYXpvbmF3",
          "cy5zZXJ2aWNlcy5zY2hlbWFyZWdpc3RyeS51dGlscy5hcGljdXJpby5zeW50",
          "YXgy"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Type.MoneyReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Foo), global::Foo.Parser, new[]{ "A", "B", "Money" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Foo : pb::IMessage<Foo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Foo> _parser = new pb::MessageParser<Foo>(() => new Foo());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Foo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::TestSyntax2JavaPackageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Foo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Foo(Foo other) : this() {
    _hasBits0 = other._hasBits0;
    a_ = other.a_;
    b_ = other.b_;
    money_ = other.money_ != null ? other.money_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Foo Clone() {
    return new Foo(this);
  }

  /// <summary>Field number for the "a" field.</summary>
  public const int AFieldNumber = 1;
  private readonly static int ADefaultValue = 0;

  private int a_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int A {
    get { if ((_hasBits0 & 1) != 0) { return a_; } else { return ADefaultValue; } }
    set {
      _hasBits0 |= 1;
      a_ = value;
    }
  }
  /// <summary>Gets whether the "a" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasA {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "a" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearA() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "b" field.</summary>
  public const int BFieldNumber = 2;
  private readonly static string BDefaultValue = "";

  private string b_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string B {
    get { return b_ ?? BDefaultValue; }
    set {
      b_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "b" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasB {
    get { return b_ != null; }
  }
  /// <summary>Clears the value of the "b" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearB() {
    b_ = null;
  }

  /// <summary>Field number for the "money" field.</summary>
  public const int MoneyFieldNumber = 5;
  private global::Google.Type.Money money_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Type.Money Money {
    get { return money_; }
    set {
      money_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Foo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Foo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (A != other.A) return false;
    if (B != other.B) return false;
    if (!object.Equals(Money, other.Money)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasA) hash ^= A.GetHashCode();
    if (HasB) hash ^= B.GetHashCode();
    if (money_ != null) hash ^= Money.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasA) {
      output.WriteRawTag(8);
      output.WriteInt32(A);
    }
    if (HasB) {
      output.WriteRawTag(18);
      output.WriteString(B);
    }
    if (money_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(Money);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasA) {
      output.WriteRawTag(8);
      output.WriteInt32(A);
    }
    if (HasB) {
      output.WriteRawTag(18);
      output.WriteString(B);
    }
    if (money_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(Money);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasA) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(A);
    }
    if (HasB) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(B);
    }
    if (money_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Money);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Foo other) {
    if (other == null) {
      return;
    }
    if (other.HasA) {
      A = other.A;
    }
    if (other.HasB) {
      B = other.B;
    }
    if (other.money_ != null) {
      if (money_ == null) {
        Money = new global::Google.Type.Money();
      }
      Money.MergeFrom(other.Money);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          A = input.ReadInt32();
          break;
        }
        case 18: {
          B = input.ReadString();
          break;
        }
        case 42: {
          if (money_ == null) {
            Money = new global::Google.Type.Money();
          }
          input.ReadMessage(Money);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          A = input.ReadInt32();
          break;
        }
        case 18: {
          B = input.ReadString();
          break;
        }
        case 42: {
          if (money_ == null) {
            Money = new global::Google.Type.Money();
          }
          input.ReadMessage(Money);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
