// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TestSyntax3JavaPackage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from TestSyntax3JavaPackage.proto</summary>
public static partial class TestSyntax3JavaPackageReflection {

  #region Descriptor
  /// <summary>File descriptor for TestSyntax3JavaPackage.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static TestSyntax3JavaPackageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChxUZXN0U3ludGF4M0phdmFQYWNrYWdlLnByb3RvGhdnb29nbGUvdHlwZS9t",
          "b25leS5wcm90byI+CgNCYXISCQoBcBgBIAEoBRIJCgFxGAIgASgJEiEKBW1v",
          "bmV5GAUgASgLMhIuZ29vZ2xlLnR5cGUuTW9uZXlCPgo8Y29tLmFtYXpvbmF3",
          "cy5zZXJ2aWNlcy5zY2hlbWFyZWdpc3RyeS51dGlscy5hcGljdXJpby5zeW50",
          "YXgzYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Type.MoneyReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Bar), global::Bar.Parser, new[]{ "P", "Q", "Money" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Bar : pb::IMessage<Bar>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Bar> _parser = new pb::MessageParser<Bar>(() => new Bar());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Bar> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::TestSyntax3JavaPackageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Bar() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Bar(Bar other) : this() {
    p_ = other.p_;
    q_ = other.q_;
    money_ = other.money_ != null ? other.money_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Bar Clone() {
    return new Bar(this);
  }

  /// <summary>Field number for the "p" field.</summary>
  public const int PFieldNumber = 1;
  private int p_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int P {
    get { return p_; }
    set {
      p_ = value;
    }
  }

  /// <summary>Field number for the "q" field.</summary>
  public const int QFieldNumber = 2;
  private string q_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Q {
    get { return q_; }
    set {
      q_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "money" field.</summary>
  public const int MoneyFieldNumber = 5;
  private global::Google.Type.Money money_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Type.Money Money {
    get { return money_; }
    set {
      money_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Bar);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Bar other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (P != other.P) return false;
    if (Q != other.Q) return false;
    if (!object.Equals(Money, other.Money)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (P != 0) hash ^= P.GetHashCode();
    if (Q.Length != 0) hash ^= Q.GetHashCode();
    if (money_ != null) hash ^= Money.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (P != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(P);
    }
    if (Q.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Q);
    }
    if (money_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(Money);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (P != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(P);
    }
    if (Q.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Q);
    }
    if (money_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(Money);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (P != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(P);
    }
    if (Q.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Q);
    }
    if (money_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Money);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Bar other) {
    if (other == null) {
      return;
    }
    if (other.P != 0) {
      P = other.P;
    }
    if (other.Q.Length != 0) {
      Q = other.Q;
    }
    if (other.money_ != null) {
      if (money_ == null) {
        Money = new global::Google.Type.Money();
      }
      Money.MergeFrom(other.Money);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          P = input.ReadInt32();
          break;
        }
        case 18: {
          Q = input.ReadString();
          break;
        }
        case 42: {
          if (money_ == null) {
            Money = new global::Google.Type.Money();
          }
          input.ReadMessage(Money);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          P = input.ReadInt32();
          break;
        }
        case 18: {
          Q = input.ReadString();
          break;
        }
        case 42: {
          if (money_ == null) {
            Money = new global::Google.Type.Money();
          }
          input.ReadMessage(Money);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
