// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TestOrderingSyntax3.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3 {

  /// <summary>Holder for reflection information generated from TestOrderingSyntax3.proto</summary>
  public static partial class TestOrderingSyntax3Reflection {

    #region Descriptor
    /// <summary>File descriptor for TestOrderingSyntax3.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestOrderingSyntax3Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlUZXN0T3JkZXJpbmdTeW50YXgzLnByb3RvEjxjb20uYW1hem9uYXdzLnNl",
            "cnZpY2VzLnNjaGVtYXJlZ2lzdHJ5LnV0aWxzLmFwaWN1cmlvLnN5bnRheDMi",
            "2AkKB0FkZHJlc3MScQoOY29udGFjdFBlcnNvbnMYBCADKAsyWS5jb20uYW1h",
            "em9uYXdzLnNlcnZpY2VzLnNjaGVtYXJlZ2lzdHJ5LnV0aWxzLmFwaWN1cmlv",
            "LnN5bnRheDMuQWRkcmVzcy5Db250YWN0UGVyc29uc0VudHJ5Eh4KBnN0cmVl",
            "dBgBIAEoCVIOQWRkcmVzc19TdHJlZXQSDwoDemlwGAIgASgFQgIYARIVCghv",
            "Y2N1cGllZBgLIAEoCEgBiAEBEmsKC2FkZHJlc3NUeXBlGAkgAygLMlYuY29t",
            "LmFtYXpvbmF3cy5zZXJ2aWNlcy5zY2hlbWFyZWdpc3RyeS51dGlscy5hcGlj",
            "dXJpby5zeW50YXgzLkFkZHJlc3MuQWRkcmVzc1R5cGVFbnRyeRIMCgRjaXR5",
            "GAMgASgJEg8KBXN0YXRlGAUgASgJSAASEQoHY291bnRyeRgHIAEoCUgAEhMK",
            "B3NhbXBsZXMYBiADKAVCAhABEm8KDXBhc3RBZGRyZXNzZXMYCCADKAsyWC5j",
            "b20uYW1hem9uYXdzLnNlcnZpY2VzLnNjaGVtYXJlZ2lzdHJ5LnV0aWxzLmFw",
            "aWN1cmlvLnN5bnRheDMuQWRkcmVzcy5QYXN0QWRkcmVzc2VzRW50cnkSbwoN",
            "cGFzdEN1c3RvbWVycxgMIAMoCzJYLmNvbS5hbWF6b25hd3Muc2VydmljZXMu",
            "c2NoZW1hcmVnaXN0cnkudXRpbHMuYXBpY3VyaW8uc3ludGF4My5BZGRyZXNz",
            "LlBhc3RDdXN0b21lcnNFbnRyeRJxCg5jb250YWN0TnVtYmVycxgKIAMoCzJZ",
            "LmNvbS5hbWF6b25hd3Muc2VydmljZXMuc2NoZW1hcmVnaXN0cnkudXRpbHMu",
            "YXBpY3VyaW8uc3ludGF4My5BZGRyZXNzLkNvbnRhY3ROdW1iZXJzRW50cnka",
            "NQoTQ29udGFjdFBlcnNvbnNFbnRyeRILCgNrZXkYASABKAUSDQoFdmFsdWUY",
            "AiABKAk6AjgBGn4KEEFkZHJlc3NUeXBlRW50cnkSCwoDa2V5GAEgASgFElkK",
            "BXZhbHVlGAIgASgOMkouY29tLmFtYXpvbmF3cy5zZXJ2aWNlcy5zY2hlbWFy",
            "ZWdpc3RyeS51dGlscy5hcGljdXJpby5zeW50YXgzLkFkZHJlc3MuVHlwZToC",
            "OAEaNAoSUGFzdEFkZHJlc3Nlc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1",
            "ZRgCIAEoCToCOAEaFQoIQ3VzdG9tZXISCQoBZhgBIAEoBRqEAQoSUGFzdEN1",
            "c3RvbWVyc0VudHJ5EgsKA2tleRgBIAEoCRJdCgV2YWx1ZRgCIAEoCzJOLmNv",
            "bS5hbWF6b25hd3Muc2VydmljZXMuc2NoZW1hcmVnaXN0cnkudXRpbHMuYXBp",
            "Y3VyaW8uc3ludGF4My5BZGRyZXNzLkN1c3RvbWVyOgI4ARo1ChNDb250YWN0",
            "TnVtYmVyc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoBToCOAEi",
            "LAoEVHlwZRIKCgZPRkZJQ0UQABINCglBUEFSVE1FTlQQARIJCgVIT1VTRRAC",
            "QgwKCnRlc3Rfb25lb2ZCCwoJX29jY3VwaWVkIqMCCghDdXN0b21lchIMCgRu",
            "YW1lGAEgASgJElYKB2FkZHJlc3MYAyABKAsyRS5jb20uYW1hem9uYXdzLnNl",
            "cnZpY2VzLnNjaGVtYXJlZ2lzdHJ5LnV0aWxzLmFwaWN1cmlvLnN5bnRheDMu",
            "QWRkcmVzcxJnCgthZGRyZXNzVHlwZRgEIAEoDjJSLmNvbS5hbWF6b25hd3Mu",
            "c2VydmljZXMuc2NoZW1hcmVnaXN0cnkudXRpbHMuYXBpY3VyaW8uc3ludGF4",
            "My5DdXN0b21lci5BZGRyZXNzVHlwZSIuCgtBZGRyZXNzVHlwZRIPCgtSRVNJ",
            "REVOVElBTBAAEg4KCkNPTU1FUkNJQUwQAUoECAIQA0oECA8QEEoECAoQDEoG",
            "CKAGEIQHYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address), global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Parser, new[]{ "ContactPersons", "Street", "Zip", "Occupied", "AddressType", "City", "State", "Country", "Samples", "PastAddresses", "PastCustomers", "ContactNumbers" }, new[]{ "TestOneof", "Occupied" }, new[]{ typeof(global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Types.Type) }, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, new pbr::GeneratedClrTypeInfo(typeof(global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Types.Customer), global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Types.Customer.Parser, new[]{ "F" }, null, null, null, null),
            null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Customer), global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Customer.Parser, new[]{ "Name", "Address", "AddressType" }, null, new[]{ typeof(global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Customer.Types.AddressType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Address : pb::IMessage<Address>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Address> _parser = new pb::MessageParser<Address>(() => new Address());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Address> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.TestOrderingSyntax3Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Address() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Address(Address other) : this() {
      _hasBits0 = other._hasBits0;
      contactPersons_ = other.contactPersons_.Clone();
      street_ = other.street_;
      zip_ = other.zip_;
      occupied_ = other.occupied_;
      addressType_ = other.addressType_.Clone();
      city_ = other.city_;
      samples_ = other.samples_.Clone();
      pastAddresses_ = other.pastAddresses_.Clone();
      pastCustomers_ = other.pastCustomers_.Clone();
      contactNumbers_ = other.contactNumbers_.Clone();
      switch (other.TestOneofCase) {
        case TestOneofOneofCase.State:
          State = other.State;
          break;
        case TestOneofOneofCase.Country:
          Country = other.Country;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Address Clone() {
      return new Address(this);
    }

    /// <summary>Field number for the "contactPersons" field.</summary>
    public const int ContactPersonsFieldNumber = 4;
    private static readonly pbc::MapField<int, string>.Codec _map_contactPersons_codec
        = new pbc::MapField<int, string>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForString(18, ""), 34);
    private readonly pbc::MapField<int, string> contactPersons_ = new pbc::MapField<int, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, string> ContactPersons {
      get { return contactPersons_; }
    }

    /// <summary>Field number for the "street" field.</summary>
    public const int StreetFieldNumber = 1;
    private string street_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Street {
      get { return street_; }
      set {
        street_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "zip" field.</summary>
    public const int ZipFieldNumber = 2;
    private int zip_;
    [global::System.ObsoleteAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Zip {
      get { return zip_; }
      set {
        zip_ = value;
      }
    }

    /// <summary>Field number for the "occupied" field.</summary>
    public const int OccupiedFieldNumber = 11;
    private bool occupied_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Occupied {
      get { if ((_hasBits0 & 1) != 0) { return occupied_; } else { return false; } }
      set {
        _hasBits0 |= 1;
        occupied_ = value;
      }
    }
    /// <summary>Gets whether the "occupied" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOccupied {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "occupied" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOccupied() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "addressType" field.</summary>
    public const int AddressTypeFieldNumber = 9;
    private static readonly pbc::MapField<int, global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Types.Type>.Codec _map_addressType_codec
        = new pbc::MapField<int, global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Types.Type>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForEnum(16, x => (int) x, x => (global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Types.Type) x, global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Types.Type.Office), 74);
    private readonly pbc::MapField<int, global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Types.Type> addressType_ = new pbc::MapField<int, global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Types.Type>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Types.Type> AddressType {
      get { return addressType_; }
    }

    /// <summary>Field number for the "city" field.</summary>
    public const int CityFieldNumber = 3;
    private string city_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string City {
      get { return city_; }
      set {
        city_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string State {
      get { return testOneofCase_ == TestOneofOneofCase.State ? (string) testOneof_ : ""; }
      set {
        testOneof_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        testOneofCase_ = TestOneofOneofCase.State;
      }
    }

    /// <summary>Field number for the "country" field.</summary>
    public const int CountryFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Country {
      get { return testOneofCase_ == TestOneofOneofCase.Country ? (string) testOneof_ : ""; }
      set {
        testOneof_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        testOneofCase_ = TestOneofOneofCase.Country;
      }
    }

    /// <summary>Field number for the "samples" field.</summary>
    public const int SamplesFieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_samples_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> samples_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Samples {
      get { return samples_; }
    }

    /// <summary>Field number for the "pastAddresses" field.</summary>
    public const int PastAddressesFieldNumber = 8;
    private static readonly pbc::MapField<string, string>.Codec _map_pastAddresses_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 66);
    private readonly pbc::MapField<string, string> pastAddresses_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> PastAddresses {
      get { return pastAddresses_; }
    }

    /// <summary>Field number for the "pastCustomers" field.</summary>
    public const int PastCustomersFieldNumber = 12;
    private static readonly pbc::MapField<string, global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Types.Customer>.Codec _map_pastCustomers_codec
        = new pbc::MapField<string, global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Types.Customer>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Types.Customer.Parser), 98);
    private readonly pbc::MapField<string, global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Types.Customer> pastCustomers_ = new pbc::MapField<string, global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Types.Customer>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Types.Customer> PastCustomers {
      get { return pastCustomers_; }
    }

    /// <summary>Field number for the "contactNumbers" field.</summary>
    public const int ContactNumbersFieldNumber = 10;
    private static readonly pbc::MapField<string, int>.Codec _map_contactNumbers_codec
        = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForInt32(16, 0), 82);
    private readonly pbc::MapField<string, int> contactNumbers_ = new pbc::MapField<string, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, int> ContactNumbers {
      get { return contactNumbers_; }
    }

    private object testOneof_;
    /// <summary>Enum of possible cases for the "test_oneof" oneof.</summary>
    public enum TestOneofOneofCase {
      None = 0,
      State = 5,
      Country = 7,
    }
    private TestOneofOneofCase testOneofCase_ = TestOneofOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestOneofOneofCase TestOneofCase {
      get { return testOneofCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTestOneof() {
      testOneofCase_ = TestOneofOneofCase.None;
      testOneof_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Address);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Address other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!ContactPersons.Equals(other.ContactPersons)) return false;
      if (Street != other.Street) return false;
      if (Zip != other.Zip) return false;
      if (Occupied != other.Occupied) return false;
      if (!AddressType.Equals(other.AddressType)) return false;
      if (City != other.City) return false;
      if (State != other.State) return false;
      if (Country != other.Country) return false;
      if(!samples_.Equals(other.samples_)) return false;
      if (!PastAddresses.Equals(other.PastAddresses)) return false;
      if (!PastCustomers.Equals(other.PastCustomers)) return false;
      if (!ContactNumbers.Equals(other.ContactNumbers)) return false;
      if (TestOneofCase != other.TestOneofCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= ContactPersons.GetHashCode();
      if (Street.Length != 0) hash ^= Street.GetHashCode();
      if (Zip != 0) hash ^= Zip.GetHashCode();
      if (HasOccupied) hash ^= Occupied.GetHashCode();
      hash ^= AddressType.GetHashCode();
      if (City.Length != 0) hash ^= City.GetHashCode();
      if (testOneofCase_ == TestOneofOneofCase.State) hash ^= State.GetHashCode();
      if (testOneofCase_ == TestOneofOneofCase.Country) hash ^= Country.GetHashCode();
      hash ^= samples_.GetHashCode();
      hash ^= PastAddresses.GetHashCode();
      hash ^= PastCustomers.GetHashCode();
      hash ^= ContactNumbers.GetHashCode();
      hash ^= (int) testOneofCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Street.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Street);
      }
      if (Zip != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Zip);
      }
      if (City.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(City);
      }
      contactPersons_.WriteTo(output, _map_contactPersons_codec);
      if (testOneofCase_ == TestOneofOneofCase.State) {
        output.WriteRawTag(42);
        output.WriteString(State);
      }
      samples_.WriteTo(output, _repeated_samples_codec);
      if (testOneofCase_ == TestOneofOneofCase.Country) {
        output.WriteRawTag(58);
        output.WriteString(Country);
      }
      pastAddresses_.WriteTo(output, _map_pastAddresses_codec);
      addressType_.WriteTo(output, _map_addressType_codec);
      contactNumbers_.WriteTo(output, _map_contactNumbers_codec);
      if (HasOccupied) {
        output.WriteRawTag(88);
        output.WriteBool(Occupied);
      }
      pastCustomers_.WriteTo(output, _map_pastCustomers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Street.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Street);
      }
      if (Zip != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Zip);
      }
      if (City.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(City);
      }
      contactPersons_.WriteTo(ref output, _map_contactPersons_codec);
      if (testOneofCase_ == TestOneofOneofCase.State) {
        output.WriteRawTag(42);
        output.WriteString(State);
      }
      samples_.WriteTo(ref output, _repeated_samples_codec);
      if (testOneofCase_ == TestOneofOneofCase.Country) {
        output.WriteRawTag(58);
        output.WriteString(Country);
      }
      pastAddresses_.WriteTo(ref output, _map_pastAddresses_codec);
      addressType_.WriteTo(ref output, _map_addressType_codec);
      contactNumbers_.WriteTo(ref output, _map_contactNumbers_codec);
      if (HasOccupied) {
        output.WriteRawTag(88);
        output.WriteBool(Occupied);
      }
      pastCustomers_.WriteTo(ref output, _map_pastCustomers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += contactPersons_.CalculateSize(_map_contactPersons_codec);
      if (Street.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Street);
      }
      if (Zip != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Zip);
      }
      if (HasOccupied) {
        size += 1 + 1;
      }
      size += addressType_.CalculateSize(_map_addressType_codec);
      if (City.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(City);
      }
      if (testOneofCase_ == TestOneofOneofCase.State) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(State);
      }
      if (testOneofCase_ == TestOneofOneofCase.Country) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Country);
      }
      size += samples_.CalculateSize(_repeated_samples_codec);
      size += pastAddresses_.CalculateSize(_map_pastAddresses_codec);
      size += pastCustomers_.CalculateSize(_map_pastCustomers_codec);
      size += contactNumbers_.CalculateSize(_map_contactNumbers_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Address other) {
      if (other == null) {
        return;
      }
      contactPersons_.Add(other.contactPersons_);
      if (other.Street.Length != 0) {
        Street = other.Street;
      }
      if (other.Zip != 0) {
        Zip = other.Zip;
      }
      if (other.HasOccupied) {
        Occupied = other.Occupied;
      }
      addressType_.Add(other.addressType_);
      if (other.City.Length != 0) {
        City = other.City;
      }
      samples_.Add(other.samples_);
      pastAddresses_.Add(other.pastAddresses_);
      pastCustomers_.Add(other.pastCustomers_);
      contactNumbers_.Add(other.contactNumbers_);
      switch (other.TestOneofCase) {
        case TestOneofOneofCase.State:
          State = other.State;
          break;
        case TestOneofOneofCase.Country:
          Country = other.Country;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Street = input.ReadString();
            break;
          }
          case 16: {
            Zip = input.ReadInt32();
            break;
          }
          case 26: {
            City = input.ReadString();
            break;
          }
          case 34: {
            contactPersons_.AddEntriesFrom(input, _map_contactPersons_codec);
            break;
          }
          case 42: {
            State = input.ReadString();
            break;
          }
          case 50:
          case 48: {
            samples_.AddEntriesFrom(input, _repeated_samples_codec);
            break;
          }
          case 58: {
            Country = input.ReadString();
            break;
          }
          case 66: {
            pastAddresses_.AddEntriesFrom(input, _map_pastAddresses_codec);
            break;
          }
          case 74: {
            addressType_.AddEntriesFrom(input, _map_addressType_codec);
            break;
          }
          case 82: {
            contactNumbers_.AddEntriesFrom(input, _map_contactNumbers_codec);
            break;
          }
          case 88: {
            Occupied = input.ReadBool();
            break;
          }
          case 98: {
            pastCustomers_.AddEntriesFrom(input, _map_pastCustomers_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Street = input.ReadString();
            break;
          }
          case 16: {
            Zip = input.ReadInt32();
            break;
          }
          case 26: {
            City = input.ReadString();
            break;
          }
          case 34: {
            contactPersons_.AddEntriesFrom(ref input, _map_contactPersons_codec);
            break;
          }
          case 42: {
            State = input.ReadString();
            break;
          }
          case 50:
          case 48: {
            samples_.AddEntriesFrom(ref input, _repeated_samples_codec);
            break;
          }
          case 58: {
            Country = input.ReadString();
            break;
          }
          case 66: {
            pastAddresses_.AddEntriesFrom(ref input, _map_pastAddresses_codec);
            break;
          }
          case 74: {
            addressType_.AddEntriesFrom(ref input, _map_addressType_codec);
            break;
          }
          case 82: {
            contactNumbers_.AddEntriesFrom(ref input, _map_contactNumbers_codec);
            break;
          }
          case 88: {
            Occupied = input.ReadBool();
            break;
          }
          case 98: {
            pastCustomers_.AddEntriesFrom(ref input, _map_pastCustomers_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Address message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("OFFICE")] Office = 0,
        [pbr::OriginalName("APARTMENT")] Apartment = 1,
        [pbr::OriginalName("HOUSE")] House = 2,
      }

      public sealed partial class Customer : pb::IMessage<Customer>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Customer> _parser = new pb::MessageParser<Customer>(() => new Customer());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Customer> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address.Descriptor.NestedTypes[3]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Customer() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Customer(Customer other) : this() {
          f_ = other.f_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Customer Clone() {
          return new Customer(this);
        }

        /// <summary>Field number for the "f" field.</summary>
        public const int FFieldNumber = 1;
        private int f_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int F {
          get { return f_; }
          set {
            f_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Customer);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Customer other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (F != other.F) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (F != 0) hash ^= F.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (F != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(F);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (F != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(F);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (F != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(F);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Customer other) {
          if (other == null) {
            return;
          }
          if (other.F != 0) {
            F = other.F;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                F = input.ReadInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                F = input.ReadInt32();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  public sealed partial class Customer : pb::IMessage<Customer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Customer> _parser = new pb::MessageParser<Customer>(() => new Customer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Customer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.TestOrderingSyntax3Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Customer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Customer(Customer other) : this() {
      name_ = other.name_;
      address_ = other.address_ != null ? other.address_.Clone() : null;
      addressType_ = other.addressType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Customer Clone() {
      return new Customer(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 3;
    private global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address address_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address Address {
      get { return address_; }
      set {
        address_ = value;
      }
    }

    /// <summary>Field number for the "addressType" field.</summary>
    public const int AddressTypeFieldNumber = 4;
    private global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Customer.Types.AddressType addressType_ = global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Customer.Types.AddressType.Residential;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Customer.Types.AddressType AddressType {
      get { return addressType_; }
      set {
        addressType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Customer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Customer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(Address, other.Address)) return false;
      if (AddressType != other.AddressType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (address_ != null) hash ^= Address.GetHashCode();
      if (AddressType != global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Customer.Types.AddressType.Residential) hash ^= AddressType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (address_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Address);
      }
      if (AddressType != global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Customer.Types.AddressType.Residential) {
        output.WriteRawTag(32);
        output.WriteEnum((int) AddressType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (address_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Address);
      }
      if (AddressType != global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Customer.Types.AddressType.Residential) {
        output.WriteRawTag(32);
        output.WriteEnum((int) AddressType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (address_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Address);
      }
      if (AddressType != global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Customer.Types.AddressType.Residential) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AddressType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Customer other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.address_ != null) {
        if (address_ == null) {
          Address = new global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address();
        }
        Address.MergeFrom(other.Address);
      }
      if (other.AddressType != global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Customer.Types.AddressType.Residential) {
        AddressType = other.AddressType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            if (address_ == null) {
              Address = new global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address();
            }
            input.ReadMessage(Address);
            break;
          }
          case 32: {
            AddressType = (global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Customer.Types.AddressType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            if (address_ == null) {
              Address = new global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Address();
            }
            input.ReadMessage(Address);
            break;
          }
          case 32: {
            AddressType = (global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax3.Customer.Types.AddressType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Customer message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum AddressType {
        [pbr::OriginalName("RESIDENTIAL")] Residential = 0,
        [pbr::OriginalName("COMMERCIAL")] Commercial = 1,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
