// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TestSyntax2OneOfs.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2 {

  /// <summary>Holder for reflection information generated from TestSyntax2OneOfs.proto</summary>
  public static partial class TestSyntax2OneOfsReflection {

    #region Descriptor
    /// <summary>File descriptor for TestSyntax2OneOfs.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestSyntax2OneOfsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdUZXN0U3ludGF4Mk9uZU9mcy5wcm90bxI8Y29tLmFtYXpvbmF3cy5zZXJ2",
            "aWNlcy5zY2hlbWFyZWdpc3RyeS51dGlscy5hcGljdXJpby5zeW50YXgyItQC",
            "CghUcmFja2luZxIOCgZvcmlnaW4YASABKAkSEwoLZGVzdGluYXRpb24YAiAB",
            "KAkSFQoLdHJhY2tpbmdOdW0YAyABKAZIABIWCgxyZWZlcmVuY2VOdW0YBCAB",
            "KBBIABIOCgZzdGF0ZXMYCiADKAkSUgoFdHlwZTEYBSABKAsyQS5jb20uYW1h",
            "em9uYXdzLnNlcnZpY2VzLnNjaGVtYXJlZ2lzdHJ5LnV0aWxzLmFwaWN1cmlv",
            "LnN5bnRheDIuRm9vSAESDwoFdHlwZTIYBiABKA1IARJWCgV0eXBlMxgJIAEo",
            "CzJFLmNvbS5hbWF6b25hd3Muc2VydmljZXMuc2NoZW1hcmVnaXN0cnkudXRp",
            "bHMuYXBpY3VyaW8uc3ludGF4Mi5NZXNzYWdlSAESFQoNdHJhY2tpbmdJbWFn",
            "ZRgHIAEoDEIICgZTdGF0dXNCBgoEdHlwZSJyCgNGb28SWAoIdHJhY2tpbmcY",
            "CyABKAsyRi5jb20uYW1hem9uYXdzLnNlcnZpY2VzLnNjaGVtYXJlZ2lzdHJ5",
            "LnV0aWxzLmFwaWN1cmlvLnN5bnRheDIuVHJhY2tpbmcSEQoJYWRkcmVzc0lk",
            "GAwgASgJItQCCgdNZXNzYWdlElcKBW5hbWV5GAEgASgLMkYuY29tLmFtYXpv",
            "bmF3cy5zZXJ2aWNlcy5zY2hlbWFyZWdpc3RyeS51dGlscy5hcGljdXJpby5z",
            "eW50YXgyLlRyYWNraW5nSAASWgoEZ2FtZRgFIAEoDjJKLmNvbS5hbWF6b25h",
            "d3Muc2VydmljZXMuc2NoZW1hcmVnaXN0cnkudXRpbHMuYXBpY3VyaW8uc3lu",
            "dGF4Mi5NZXNzYWdlLkdhbWVIABIMCgRuYW1lGAIgAigJEhIKCm90aGVyX25h",
            "bWUYAyACKAgSDwoFbmFtZXIYBCABKAlIARoWCgZOZXN0ZWQSDAoEbmFtZRgC",
            "IAIoCSIkCgRHYW1lEgwKCFJFRExJR0hUEBYSDgoKR1JFRU5MSUdIVBAYKgYI",
            "9AMQ9gMqBgj3AxD4A0IICgZ0aGluZ3lCCQoHdGhpbmdlcg=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Tracking), global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Tracking.Parser, new[]{ "Origin", "Destination", "TrackingNum", "ReferenceNum", "States", "Type1", "Type2", "Type3", "TrackingImage" }, new[]{ "Status", "Type" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Foo), global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Foo.Parser, new[]{ "Tracking", "AddressId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Message), global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Message.Parser, new[]{ "Namey", "Game", "Name", "OtherName", "Namer" }, new[]{ "Thingy", "Thinger" }, new[]{ typeof(global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Message.Types.Game) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Message.Types.Nested), global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Message.Types.Nested.Parser, new[]{ "Name" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Tracking : pb::IMessage<Tracking>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Tracking> _parser = new pb::MessageParser<Tracking>(() => new Tracking());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Tracking> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.TestSyntax2OneOfsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Tracking() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Tracking(Tracking other) : this() {
      origin_ = other.origin_;
      destination_ = other.destination_;
      states_ = other.states_.Clone();
      trackingImage_ = other.trackingImage_;
      switch (other.StatusCase) {
        case StatusOneofCase.TrackingNum:
          TrackingNum = other.TrackingNum;
          break;
        case StatusOneofCase.ReferenceNum:
          ReferenceNum = other.ReferenceNum;
          break;
      }

      switch (other.TypeCase) {
        case TypeOneofCase.Type1:
          Type1 = other.Type1.Clone();
          break;
        case TypeOneofCase.Type2:
          Type2 = other.Type2;
          break;
        case TypeOneofCase.Type3:
          Type3 = other.Type3.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Tracking Clone() {
      return new Tracking(this);
    }

    /// <summary>Field number for the "origin" field.</summary>
    public const int OriginFieldNumber = 1;
    private readonly static string OriginDefaultValue = "";

    private string origin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Origin {
      get { return origin_ ?? OriginDefaultValue; }
      set {
        origin_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "origin" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOrigin {
      get { return origin_ != null; }
    }
    /// <summary>Clears the value of the "origin" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOrigin() {
      origin_ = null;
    }

    /// <summary>Field number for the "destination" field.</summary>
    public const int DestinationFieldNumber = 2;
    private readonly static string DestinationDefaultValue = "";

    private string destination_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Destination {
      get { return destination_ ?? DestinationDefaultValue; }
      set {
        destination_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "destination" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDestination {
      get { return destination_ != null; }
    }
    /// <summary>Clears the value of the "destination" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDestination() {
      destination_ = null;
    }

    /// <summary>Field number for the "trackingNum" field.</summary>
    public const int TrackingNumFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TrackingNum {
      get { return HasTrackingNum ? (ulong) status_ : 0UL; }
      set {
        status_ = value;
        statusCase_ = StatusOneofCase.TrackingNum;
      }
    }
    /// <summary>Gets whether the "trackingNum" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTrackingNum {
      get { return statusCase_ == StatusOneofCase.TrackingNum; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "trackingNum" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTrackingNum() {
      if (HasTrackingNum) {
        ClearStatus();
      }
    }

    /// <summary>Field number for the "referenceNum" field.</summary>
    public const int ReferenceNumFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ReferenceNum {
      get { return HasReferenceNum ? (long) status_ : 0L; }
      set {
        status_ = value;
        statusCase_ = StatusOneofCase.ReferenceNum;
      }
    }
    /// <summary>Gets whether the "referenceNum" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasReferenceNum {
      get { return statusCase_ == StatusOneofCase.ReferenceNum; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "referenceNum" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearReferenceNum() {
      if (HasReferenceNum) {
        ClearStatus();
      }
    }

    /// <summary>Field number for the "states" field.</summary>
    public const int StatesFieldNumber = 10;
    private static readonly pb::FieldCodec<string> _repeated_states_codec
        = pb::FieldCodec.ForString(82);
    private readonly pbc::RepeatedField<string> states_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> States {
      get { return states_; }
    }

    /// <summary>Field number for the "type1" field.</summary>
    public const int Type1FieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Foo Type1 {
      get { return typeCase_ == TypeOneofCase.Type1 ? (global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Foo) type_ : null; }
      set {
        type_ = value;
        typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.Type1;
      }
    }

    /// <summary>Field number for the "type2" field.</summary>
    public const int Type2FieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Type2 {
      get { return HasType2 ? (uint) type_ : 0; }
      set {
        type_ = value;
        typeCase_ = TypeOneofCase.Type2;
      }
    }
    /// <summary>Gets whether the "type2" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasType2 {
      get { return typeCase_ == TypeOneofCase.Type2; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "type2" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearType2() {
      if (HasType2) {
        ClearType();
      }
    }

    /// <summary>Field number for the "type3" field.</summary>
    public const int Type3FieldNumber = 9;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Message Type3 {
      get { return typeCase_ == TypeOneofCase.Type3 ? (global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Message) type_ : null; }
      set {
        type_ = value;
        typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.Type3;
      }
    }

    /// <summary>Field number for the "trackingImage" field.</summary>
    public const int TrackingImageFieldNumber = 7;
    private readonly static pb::ByteString TrackingImageDefaultValue = pb::ByteString.Empty;

    private pb::ByteString trackingImage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString TrackingImage {
      get { return trackingImage_ ?? TrackingImageDefaultValue; }
      set {
        trackingImage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "trackingImage" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTrackingImage {
      get { return trackingImage_ != null; }
    }
    /// <summary>Clears the value of the "trackingImage" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTrackingImage() {
      trackingImage_ = null;
    }

    private object status_;
    /// <summary>Enum of possible cases for the "Status" oneof.</summary>
    public enum StatusOneofCase {
      None = 0,
      TrackingNum = 3,
      ReferenceNum = 4,
    }
    private StatusOneofCase statusCase_ = StatusOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StatusOneofCase StatusCase {
      get { return statusCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStatus() {
      statusCase_ = StatusOneofCase.None;
      status_ = null;
    }

    private object type_;
    /// <summary>Enum of possible cases for the "type" oneof.</summary>
    public enum TypeOneofCase {
      None = 0,
      Type1 = 5,
      Type2 = 6,
      Type3 = 9,
    }
    private TypeOneofCase typeCase_ = TypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TypeOneofCase TypeCase {
      get { return typeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearType() {
      typeCase_ = TypeOneofCase.None;
      type_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Tracking);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Tracking other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Origin != other.Origin) return false;
      if (Destination != other.Destination) return false;
      if (TrackingNum != other.TrackingNum) return false;
      if (ReferenceNum != other.ReferenceNum) return false;
      if(!states_.Equals(other.states_)) return false;
      if (!object.Equals(Type1, other.Type1)) return false;
      if (Type2 != other.Type2) return false;
      if (!object.Equals(Type3, other.Type3)) return false;
      if (TrackingImage != other.TrackingImage) return false;
      if (StatusCase != other.StatusCase) return false;
      if (TypeCase != other.TypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOrigin) hash ^= Origin.GetHashCode();
      if (HasDestination) hash ^= Destination.GetHashCode();
      if (HasTrackingNum) hash ^= TrackingNum.GetHashCode();
      if (HasReferenceNum) hash ^= ReferenceNum.GetHashCode();
      hash ^= states_.GetHashCode();
      if (typeCase_ == TypeOneofCase.Type1) hash ^= Type1.GetHashCode();
      if (HasType2) hash ^= Type2.GetHashCode();
      if (typeCase_ == TypeOneofCase.Type3) hash ^= Type3.GetHashCode();
      if (HasTrackingImage) hash ^= TrackingImage.GetHashCode();
      hash ^= (int) statusCase_;
      hash ^= (int) typeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasOrigin) {
        output.WriteRawTag(10);
        output.WriteString(Origin);
      }
      if (HasDestination) {
        output.WriteRawTag(18);
        output.WriteString(Destination);
      }
      if (HasTrackingNum) {
        output.WriteRawTag(25);
        output.WriteFixed64(TrackingNum);
      }
      if (HasReferenceNum) {
        output.WriteRawTag(33);
        output.WriteSFixed64(ReferenceNum);
      }
      if (typeCase_ == TypeOneofCase.Type1) {
        output.WriteRawTag(42);
        output.WriteMessage(Type1);
      }
      if (HasType2) {
        output.WriteRawTag(48);
        output.WriteUInt32(Type2);
      }
      if (HasTrackingImage) {
        output.WriteRawTag(58);
        output.WriteBytes(TrackingImage);
      }
      if (typeCase_ == TypeOneofCase.Type3) {
        output.WriteRawTag(74);
        output.WriteMessage(Type3);
      }
      states_.WriteTo(output, _repeated_states_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasOrigin) {
        output.WriteRawTag(10);
        output.WriteString(Origin);
      }
      if (HasDestination) {
        output.WriteRawTag(18);
        output.WriteString(Destination);
      }
      if (HasTrackingNum) {
        output.WriteRawTag(25);
        output.WriteFixed64(TrackingNum);
      }
      if (HasReferenceNum) {
        output.WriteRawTag(33);
        output.WriteSFixed64(ReferenceNum);
      }
      if (typeCase_ == TypeOneofCase.Type1) {
        output.WriteRawTag(42);
        output.WriteMessage(Type1);
      }
      if (HasType2) {
        output.WriteRawTag(48);
        output.WriteUInt32(Type2);
      }
      if (HasTrackingImage) {
        output.WriteRawTag(58);
        output.WriteBytes(TrackingImage);
      }
      if (typeCase_ == TypeOneofCase.Type3) {
        output.WriteRawTag(74);
        output.WriteMessage(Type3);
      }
      states_.WriteTo(ref output, _repeated_states_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasOrigin) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Origin);
      }
      if (HasDestination) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Destination);
      }
      if (HasTrackingNum) {
        size += 1 + 8;
      }
      if (HasReferenceNum) {
        size += 1 + 8;
      }
      size += states_.CalculateSize(_repeated_states_codec);
      if (typeCase_ == TypeOneofCase.Type1) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Type1);
      }
      if (HasType2) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Type2);
      }
      if (typeCase_ == TypeOneofCase.Type3) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Type3);
      }
      if (HasTrackingImage) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(TrackingImage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Tracking other) {
      if (other == null) {
        return;
      }
      if (other.HasOrigin) {
        Origin = other.Origin;
      }
      if (other.HasDestination) {
        Destination = other.Destination;
      }
      states_.Add(other.states_);
      if (other.HasTrackingImage) {
        TrackingImage = other.TrackingImage;
      }
      switch (other.StatusCase) {
        case StatusOneofCase.TrackingNum:
          TrackingNum = other.TrackingNum;
          break;
        case StatusOneofCase.ReferenceNum:
          ReferenceNum = other.ReferenceNum;
          break;
      }

      switch (other.TypeCase) {
        case TypeOneofCase.Type1:
          if (Type1 == null) {
            Type1 = new global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Foo();
          }
          Type1.MergeFrom(other.Type1);
          break;
        case TypeOneofCase.Type2:
          Type2 = other.Type2;
          break;
        case TypeOneofCase.Type3:
          if (Type3 == null) {
            Type3 = new global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Message();
          }
          Type3.MergeFrom(other.Type3);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Origin = input.ReadString();
            break;
          }
          case 18: {
            Destination = input.ReadString();
            break;
          }
          case 25: {
            TrackingNum = input.ReadFixed64();
            break;
          }
          case 33: {
            ReferenceNum = input.ReadSFixed64();
            break;
          }
          case 42: {
            global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Foo subBuilder = new global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Foo();
            if (typeCase_ == TypeOneofCase.Type1) {
              subBuilder.MergeFrom(Type1);
            }
            input.ReadMessage(subBuilder);
            Type1 = subBuilder;
            break;
          }
          case 48: {
            Type2 = input.ReadUInt32();
            break;
          }
          case 58: {
            TrackingImage = input.ReadBytes();
            break;
          }
          case 74: {
            global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Message subBuilder = new global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Message();
            if (typeCase_ == TypeOneofCase.Type3) {
              subBuilder.MergeFrom(Type3);
            }
            input.ReadMessage(subBuilder);
            Type3 = subBuilder;
            break;
          }
          case 82: {
            states_.AddEntriesFrom(input, _repeated_states_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Origin = input.ReadString();
            break;
          }
          case 18: {
            Destination = input.ReadString();
            break;
          }
          case 25: {
            TrackingNum = input.ReadFixed64();
            break;
          }
          case 33: {
            ReferenceNum = input.ReadSFixed64();
            break;
          }
          case 42: {
            global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Foo subBuilder = new global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Foo();
            if (typeCase_ == TypeOneofCase.Type1) {
              subBuilder.MergeFrom(Type1);
            }
            input.ReadMessage(subBuilder);
            Type1 = subBuilder;
            break;
          }
          case 48: {
            Type2 = input.ReadUInt32();
            break;
          }
          case 58: {
            TrackingImage = input.ReadBytes();
            break;
          }
          case 74: {
            global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Message subBuilder = new global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Message();
            if (typeCase_ == TypeOneofCase.Type3) {
              subBuilder.MergeFrom(Type3);
            }
            input.ReadMessage(subBuilder);
            Type3 = subBuilder;
            break;
          }
          case 82: {
            states_.AddEntriesFrom(ref input, _repeated_states_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Foo : pb::IMessage<Foo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Foo> _parser = new pb::MessageParser<Foo>(() => new Foo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Foo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.TestSyntax2OneOfsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Foo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Foo(Foo other) : this() {
      tracking_ = other.tracking_ != null ? other.tracking_.Clone() : null;
      addressId_ = other.addressId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Foo Clone() {
      return new Foo(this);
    }

    /// <summary>Field number for the "tracking" field.</summary>
    public const int TrackingFieldNumber = 11;
    private global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Tracking tracking_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Tracking Tracking {
      get { return tracking_; }
      set {
        tracking_ = value;
      }
    }

    /// <summary>Field number for the "addressId" field.</summary>
    public const int AddressIdFieldNumber = 12;
    private readonly static string AddressIdDefaultValue = "";

    private string addressId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AddressId {
      get { return addressId_ ?? AddressIdDefaultValue; }
      set {
        addressId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "addressId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAddressId {
      get { return addressId_ != null; }
    }
    /// <summary>Clears the value of the "addressId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAddressId() {
      addressId_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Foo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Foo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Tracking, other.Tracking)) return false;
      if (AddressId != other.AddressId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (tracking_ != null) hash ^= Tracking.GetHashCode();
      if (HasAddressId) hash ^= AddressId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (tracking_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Tracking);
      }
      if (HasAddressId) {
        output.WriteRawTag(98);
        output.WriteString(AddressId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (tracking_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Tracking);
      }
      if (HasAddressId) {
        output.WriteRawTag(98);
        output.WriteString(AddressId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (tracking_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Tracking);
      }
      if (HasAddressId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AddressId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Foo other) {
      if (other == null) {
        return;
      }
      if (other.tracking_ != null) {
        if (tracking_ == null) {
          Tracking = new global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Tracking();
        }
        Tracking.MergeFrom(other.Tracking);
      }
      if (other.HasAddressId) {
        AddressId = other.AddressId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 90: {
            if (tracking_ == null) {
              Tracking = new global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Tracking();
            }
            input.ReadMessage(Tracking);
            break;
          }
          case 98: {
            AddressId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 90: {
            if (tracking_ == null) {
              Tracking = new global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Tracking();
            }
            input.ReadMessage(Tracking);
            break;
          }
          case 98: {
            AddressId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Message : pb::IExtendableMessage<Message>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Message> _parser = new pb::MessageParser<Message>(() => new Message());
    private pb::UnknownFieldSet _unknownFields;
    private pb::ExtensionSet<Message> _extensions;
    private pb::ExtensionSet<Message> _Extensions { get { return _extensions; } }
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Message> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.TestSyntax2OneOfsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message(Message other) : this() {
      _hasBits0 = other._hasBits0;
      name_ = other.name_;
      otherName_ = other.otherName_;
      switch (other.ThingyCase) {
        case ThingyOneofCase.Namey:
          Namey = other.Namey.Clone();
          break;
        case ThingyOneofCase.Game:
          Game = other.Game;
          break;
      }

      switch (other.ThingerCase) {
        case ThingerOneofCase.Namer:
          Namer = other.Namer;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      _extensions = pb::ExtensionSet.Clone(other._extensions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message Clone() {
      return new Message(this);
    }

    /// <summary>Field number for the "namey" field.</summary>
    public const int NameyFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Tracking Namey {
      get { return thingyCase_ == ThingyOneofCase.Namey ? (global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Tracking) thingy_ : null; }
      set {
        thingy_ = value;
        thingyCase_ = value == null ? ThingyOneofCase.None : ThingyOneofCase.Namey;
      }
    }

    /// <summary>Field number for the "game" field.</summary>
    public const int GameFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Message.Types.Game Game {
      get { return HasGame ? (global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Message.Types.Game) thingy_ : global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Message.Types.Game.Redlight; }
      set {
        thingy_ = value;
        thingyCase_ = ThingyOneofCase.Game;
      }
    }
    /// <summary>Gets whether the "game" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGame {
      get { return thingyCase_ == ThingyOneofCase.Game; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "game" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGame() {
      if (HasGame) {
        ClearThingy();
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private readonly static string NameDefaultValue = "";

    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? NameDefaultValue; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "other_name" field.</summary>
    public const int OtherNameFieldNumber = 3;
    private readonly static bool OtherNameDefaultValue = false;

    private bool otherName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OtherName {
      get { if ((_hasBits0 & 1) != 0) { return otherName_; } else { return OtherNameDefaultValue; } }
      set {
        _hasBits0 |= 1;
        otherName_ = value;
      }
    }
    /// <summary>Gets whether the "other_name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOtherName {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "other_name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOtherName() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "namer" field.</summary>
    public const int NamerFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Namer {
      get { return HasNamer ? (string) thinger_ : ""; }
      set {
        thinger_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        thingerCase_ = ThingerOneofCase.Namer;
      }
    }
    /// <summary>Gets whether the "namer" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNamer {
      get { return thingerCase_ == ThingerOneofCase.Namer; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "namer" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNamer() {
      if (HasNamer) {
        ClearThinger();
      }
    }

    private object thingy_;
    /// <summary>Enum of possible cases for the "thingy" oneof.</summary>
    public enum ThingyOneofCase {
      None = 0,
      Namey = 1,
      Game = 5,
    }
    private ThingyOneofCase thingyCase_ = ThingyOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThingyOneofCase ThingyCase {
      get { return thingyCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearThingy() {
      thingyCase_ = ThingyOneofCase.None;
      thingy_ = null;
    }

    private object thinger_;
    /// <summary>Enum of possible cases for the "thinger" oneof.</summary>
    public enum ThingerOneofCase {
      None = 0,
      Namer = 4,
    }
    private ThingerOneofCase thingerCase_ = ThingerOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThingerOneofCase ThingerCase {
      get { return thingerCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearThinger() {
      thingerCase_ = ThingerOneofCase.None;
      thinger_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Message);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Message other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Namey, other.Namey)) return false;
      if (Game != other.Game) return false;
      if (Name != other.Name) return false;
      if (OtherName != other.OtherName) return false;
      if (Namer != other.Namer) return false;
      if (ThingyCase != other.ThingyCase) return false;
      if (ThingerCase != other.ThingerCase) return false;
      if (!Equals(_extensions, other._extensions)) {
        return false;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (thingyCase_ == ThingyOneofCase.Namey) hash ^= Namey.GetHashCode();
      if (HasGame) hash ^= Game.GetHashCode();
      if (HasName) hash ^= Name.GetHashCode();
      if (HasOtherName) hash ^= OtherName.GetHashCode();
      if (HasNamer) hash ^= Namer.GetHashCode();
      hash ^= (int) thingyCase_;
      hash ^= (int) thingerCase_;
      if (_extensions != null) {
        hash ^= _extensions.GetHashCode();
      }
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (thingyCase_ == ThingyOneofCase.Namey) {
        output.WriteRawTag(10);
        output.WriteMessage(Namey);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasOtherName) {
        output.WriteRawTag(24);
        output.WriteBool(OtherName);
      }
      if (HasNamer) {
        output.WriteRawTag(34);
        output.WriteString(Namer);
      }
      if (HasGame) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Game);
      }
      if (_extensions != null) {
        _extensions.WriteTo(output);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (thingyCase_ == ThingyOneofCase.Namey) {
        output.WriteRawTag(10);
        output.WriteMessage(Namey);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasOtherName) {
        output.WriteRawTag(24);
        output.WriteBool(OtherName);
      }
      if (HasNamer) {
        output.WriteRawTag(34);
        output.WriteString(Namer);
      }
      if (HasGame) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Game);
      }
      if (_extensions != null) {
        _extensions.WriteTo(ref output);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (thingyCase_ == ThingyOneofCase.Namey) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Namey);
      }
      if (HasGame) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Game);
      }
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasOtherName) {
        size += 1 + 1;
      }
      if (HasNamer) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Namer);
      }
      if (_extensions != null) {
        size += _extensions.CalculateSize();
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Message other) {
      if (other == null) {
        return;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasOtherName) {
        OtherName = other.OtherName;
      }
      switch (other.ThingyCase) {
        case ThingyOneofCase.Namey:
          if (Namey == null) {
            Namey = new global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Tracking();
          }
          Namey.MergeFrom(other.Namey);
          break;
        case ThingyOneofCase.Game:
          Game = other.Game;
          break;
      }

      switch (other.ThingerCase) {
        case ThingerOneofCase.Namer:
          Namer = other.Namer;
          break;
      }

      pb::ExtensionSet.MergeFrom(ref _extensions, other._extensions);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            if (!pb::ExtensionSet.TryMergeFieldFrom(ref _extensions, input)) {
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            }
            break;
          case 10: {
            global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Tracking subBuilder = new global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Tracking();
            if (thingyCase_ == ThingyOneofCase.Namey) {
              subBuilder.MergeFrom(Namey);
            }
            input.ReadMessage(subBuilder);
            Namey = subBuilder;
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            OtherName = input.ReadBool();
            break;
          }
          case 34: {
            Namer = input.ReadString();
            break;
          }
          case 40: {
            thingy_ = input.ReadEnum();
            thingyCase_ = ThingyOneofCase.Game;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            if (!pb::ExtensionSet.TryMergeFieldFrom(ref _extensions, ref input)) {
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            }
            break;
          case 10: {
            global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Tracking subBuilder = new global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Tracking();
            if (thingyCase_ == ThingyOneofCase.Namey) {
              subBuilder.MergeFrom(Namey);
            }
            input.ReadMessage(subBuilder);
            Namey = subBuilder;
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            OtherName = input.ReadBool();
            break;
          }
          case 34: {
            Namer = input.ReadString();
            break;
          }
          case 40: {
            thingy_ = input.ReadEnum();
            thingyCase_ = ThingyOneofCase.Game;
            break;
          }
        }
      }
    }
    #endif

    public TValue GetExtension<TValue>(pb::Extension<Message, TValue> extension) {
      return pb::ExtensionSet.Get(ref _extensions, extension);
    }
    public pbc::RepeatedField<TValue> GetExtension<TValue>(pb::RepeatedExtension<Message, TValue> extension) {
      return pb::ExtensionSet.Get(ref _extensions, extension);
    }
    public pbc::RepeatedField<TValue> GetOrInitializeExtension<TValue>(pb::RepeatedExtension<Message, TValue> extension) {
      return pb::ExtensionSet.GetOrInitialize(ref _extensions, extension);
    }
    public void SetExtension<TValue>(pb::Extension<Message, TValue> extension, TValue value) {
      pb::ExtensionSet.Set(ref _extensions, extension, value);
    }
    public bool HasExtension<TValue>(pb::Extension<Message, TValue> extension) {
      return pb::ExtensionSet.Has(ref _extensions, extension);
    }
    public void ClearExtension<TValue>(pb::Extension<Message, TValue> extension) {
      pb::ExtensionSet.Clear(ref _extensions, extension);
    }
    public void ClearExtension<TValue>(pb::RepeatedExtension<Message, TValue> extension) {
      pb::ExtensionSet.Clear(ref _extensions, extension);
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Message message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Game {
        [pbr::OriginalName("REDLIGHT")] Redlight = 22,
        [pbr::OriginalName("GREENLIGHT")] Greenlight = 24,
      }

      public sealed partial class Nested : pb::IMessage<Nested>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Nested> _parser = new pb::MessageParser<Nested>(() => new Nested());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Nested> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.Message.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Nested() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Nested(Nested other) : this() {
          name_ = other.name_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Nested Clone() {
          return new Nested(this);
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 2;
        private readonly static string NameDefaultValue = "";

        private string name_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name {
          get { return name_ ?? NameDefaultValue; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "name" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasName {
          get { return name_ != null; }
        }
        /// <summary>Clears the value of the "name" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearName() {
          name_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Nested);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Nested other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Name != other.Name) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasName) hash ^= Name.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasName) {
            output.WriteRawTag(18);
            output.WriteString(Name);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasName) {
            output.WriteRawTag(18);
            output.WriteString(Name);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasName) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Nested other) {
          if (other == null) {
            return;
          }
          if (other.HasName) {
            Name = other.Name;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 18: {
                Name = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 18: {
                Name = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
