// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WellKnownTypesTestSyntax2.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2 {

  /// <summary>Holder for reflection information generated from WellKnownTypesTestSyntax2.proto</summary>
  public static partial class WellKnownTypesTestSyntax2Reflection {

    #region Descriptor
    /// <summary>File descriptor for WellKnownTypesTestSyntax2.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WellKnownTypesTestSyntax2Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9XZWxsS25vd25UeXBlc1Rlc3RTeW50YXgyLnByb3RvEjxjb20uYW1hem9u",
            "YXdzLnNlcnZpY2VzLnNjaGVtYXJlZ2lzdHJ5LnV0aWxzLmFwaWN1cmlvLnN5",
            "bnRheDIaGWdvb2dsZS9wcm90b2J1Zi9hbnkucHJvdG8aGWdvb2dsZS9wcm90",
            "b2J1Zi9hcGkucHJvdG8aHmdvb2dsZS9wcm90b2J1Zi9kdXJhdGlvbi5wcm90",
            "bxobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvGiBnb29nbGUvcHJvdG9i",
            "dWYvZmllbGRfbWFzay5wcm90bxokZ29vZ2xlL3Byb3RvYnVmL3NvdXJjZV9j",
            "b250ZXh0LnByb3RvGhxnb29nbGUvcHJvdG9idWYvc3RydWN0LnByb3RvGh9n",
            "b29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvGhpnb29nbGUvcHJvdG9i",
            "dWYvdHlwZS5wcm90bxoeZ29vZ2xlL3Byb3RvYnVmL3dyYXBwZXJzLnByb3Rv",
            "GiFnb29nbGUvdHlwZS9jYWxlbmRhcl9wZXJpb2QucHJvdG8aF2dvb2dsZS90",
            "eXBlL2NvbG9yLnByb3RvGhZnb29nbGUvdHlwZS9kYXRlLnByb3RvGhtnb29n",
            "bGUvdHlwZS9kYXlvZndlZWsucHJvdG8aFmdvb2dsZS90eXBlL2V4cHIucHJv",
            "dG8aGmdvb2dsZS90eXBlL2ZyYWN0aW9uLnByb3RvGhhnb29nbGUvdHlwZS9s",
            "YXRsbmcucHJvdG8aF2dvb2dsZS90eXBlL21vbmV5LnByb3RvGhdnb29nbGUv",
            "dHlwZS9tb250aC5wcm90bxogZ29vZ2xlL3R5cGUvcG9zdGFsX2FkZHJlc3Mu",
            "cHJvdG8aHGdvb2dsZS90eXBlL3F1YXRlcm5pb24ucHJvdG8aG2dvb2dsZS90",
            "eXBlL3RpbWVvZmRheS5wcm90bxoeZ29vZ2xlL3R5cGUvcGhvbmVfbnVtYmVy",
            "LnByb3RvGiBnb29nbGUvdHlwZS9sb2NhbGl6ZWRfdGV4dC5wcm90bxoaZ29v",
            "Z2xlL3R5cGUvaW50ZXJ2YWwucHJvdG8iiw4KFVdlbGxLbm93blR5cGVzU3lu",
            "dGF4MxIJCgFhGGQgAigFEgoKAmJnGGUgAygJEhAKCGZsb2F0aW5nGGYgAigC",
            "EiEKA2YxOBgSIAMoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnkSJwoDZjI0GBgg",
            "ASgLMhouZ29vZ2xlLnByb3RvYnVmLkJvb2xWYWx1ZRIoCgNmMjUYGSABKAsy",
            "Gy5nb29nbGUucHJvdG9idWYuQnl0ZXNWYWx1ZRIpCgNmMjYYGiABKAsyHC5n",
            "b29nbGUucHJvdG9idWYuRG91YmxlVmFsdWUSJQoCZjUYBSACKAsyGS5nb29n",
            "bGUucHJvdG9idWYuRHVyYXRpb24SIgoCZjQYBCACKAsyFi5nb29nbGUucHJv",
            "dG9idWYuRW1wdHkSJwoCZjMYAyABKAsyGy5nb29nbGUucHJvdG9idWYuRmxv",
            "YXRWYWx1ZRIoCgNmMjcYGyABKAsyGy5nb29nbGUucHJvdG9idWYuSW50MzJW",
            "YWx1ZRIoCgNmMjgYHCABKAsyGy5nb29nbGUucHJvdG9idWYuSW50NjRWYWx1",
            "ZRInCgNmMjIYFiABKAsyGi5nb29nbGUucHJvdG9idWYuTGlzdFZhbHVlEicK",
            "A2YyORgdIAEoDjIaLmdvb2dsZS5wcm90b2J1Zi5OdWxsVmFsdWUSKAoCZjIY",
            "AiACKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSJAoDZjMzGCEg",
            "ASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdBImCgJmMRgBIAEoCzIaLmdv",
            "b2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASKQoDZjM0GCIgASgLMhwuZ29vZ2xl",
            "LnByb3RvYnVmLlVJbnQzMlZhbHVlEikKA2YzNRgjIAEoCzIcLmdvb2dsZS5w",
            "cm90b2J1Zi5VSW50NjRWYWx1ZRIjCgNmMzYYJCABKAsyFi5nb29nbGUucHJv",
            "dG9idWYuVmFsdWUSIQoDZjM3GCUgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFw",
            "aRInCgNmMzgYJiABKAsyGi5nb29nbGUucHJvdG9idWYuRmllbGRNYXNrEisK",
            "A2YzORgnIAEoCzIeLmdvb2dsZS5wcm90b2J1Zi5Tb3VyY2VDb250ZXh0EiIK",
            "A2Y0MRgpIAEoCzIVLmdvb2dsZS5wcm90b2J1Zi5UeXBlEiIKA2Y0MhgqIAEo",
            "CzIVLmdvb2dsZS5wcm90b2J1Zi5FbnVtEicKA2Y0MxgrIAEoCzIaLmdvb2ds",
            "ZS5wcm90b2J1Zi5FbnVtVmFsdWUSIwoDZjQ0GCwgASgLMhYuZ29vZ2xlLnBy",
            "b3RvYnVmLkZpZWxkEi8KA2Y0NRgtIAEoDjIiLmdvb2dsZS5wcm90b2J1Zi5G",
            "aWVsZC5DYXJkaW5hbGl0eRIoCgNmNDYYLiABKA4yGy5nb29nbGUucHJvdG9i",
            "dWYuRmllbGQuS2luZBIkCgNmNDcYLyABKAsyFy5nb29nbGUucHJvdG9idWYu",
            "TWV0aG9kEiMKA2Y0OBgwIAEoCzIWLmdvb2dsZS5wcm90b2J1Zi5NaXhpbhIk",
            "CgNmNDkYMSABKAsyFy5nb29nbGUucHJvdG9idWYuT3B0aW9uEiQKA2Y1MBgy",
            "IAEoDjIXLmdvb2dsZS5wcm90b2J1Zi5TeW50YXgSJwoCZjkYCSACKA4yGy5n",
            "b29nbGUudHlwZS5DYWxlbmRhclBlcmlvZBIfCgNmMTAYCiABKAsyEi5nb29n",
            "bGUudHlwZS5Db2xvchIdCgJmNxgHIAIoCzIRLmdvb2dsZS50eXBlLkRhdGUS",
            "IwoDZjExGAsgASgOMhYuZ29vZ2xlLnR5cGUuRGF5T2ZXZWVrEh4KA2YyMBgU",
            "IAEoCzIRLmdvb2dsZS50eXBlLkV4cHISIgoDZjEzGA0gAigLMhUuZ29vZ2xl",
            "LnR5cGUuRnJhY3Rpb24SIAoDZjEyGAwgASgLMhMuZ29vZ2xlLnR5cGUuTGF0",
            "TG5nEh4KAmY2GAYgAigLMhIuZ29vZ2xlLnR5cGUuTW9uZXkSHwoDZjE0GA4g",
            "AigOMhIuZ29vZ2xlLnR5cGUuTW9udGgSJwoDZjE2GBAgASgLMhouZ29vZ2xl",
            "LnR5cGUuUG9zdGFsQWRkcmVzcxIkCgNmMjEYFSADKAsyFy5nb29nbGUudHlw",
            "ZS5RdWF0ZXJuaW9uEiIKAmY4GAggASgLMhYuZ29vZ2xlLnR5cGUuVGltZU9m",
            "RGF5EiUKA2YxNRgPIAEoCzIYLmdvb2dsZS50eXBlLlBob25lTnVtYmVyEicK",
            "A2YxNxgRIAEoCzIaLmdvb2dsZS50eXBlLkxvY2FsaXplZFRleHQSIgoDZjE5",
            "GBMgAygLMhUuZ29vZ2xlLnR5cGUuSW50ZXJ2YWw="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.ApiReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.FieldMaskReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.SourceContextReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TypeReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Google.Type.CalendarPeriodReflection.Descriptor, global::Google.Type.ColorReflection.Descriptor, global::Google.Type.DateReflection.Descriptor, global::Google.Type.DayofweekReflection.Descriptor, global::Google.Type.ExprReflection.Descriptor, global::Google.Type.FractionReflection.Descriptor, global::Google.Type.LatlngReflection.Descriptor, global::Google.Type.MoneyReflection.Descriptor, global::Google.Type.MonthReflection.Descriptor, global::Google.Type.PostalAddressReflection.Descriptor, global::Google.Type.QuaternionReflection.Descriptor, global::Google.Type.TimeofdayReflection.Descriptor, global::Google.Type.PhoneNumberReflection.Descriptor, global::Google.Type.LocalizedTextReflection.Descriptor, global::Google.Type.IntervalReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.WellKnownTypesSyntax3), global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.WellKnownTypesSyntax3.Parser, new[]{ "A", "Bg", "Floating", "F18", "F24", "F25", "F26", "F5", "F4", "F3", "F27", "F28", "F22", "F29", "F2", "F33", "F1", "F34", "F35", "F36", "F37", "F38", "F39", "F41", "F42", "F43", "F44", "F45", "F46", "F47", "F48", "F49", "F50", "F9", "F10", "F7", "F11", "F20", "F13", "F12", "F6", "F14", "F16", "F21", "F8", "F15", "F17", "F19" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class WellKnownTypesSyntax3 : pb::IMessage<WellKnownTypesSyntax3>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WellKnownTypesSyntax3> _parser = new pb::MessageParser<WellKnownTypesSyntax3>(() => new WellKnownTypesSyntax3());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WellKnownTypesSyntax3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Amazonaws.Services.Schemaregistry.Utils.Apicurio.Syntax2.WellKnownTypesTestSyntax2Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WellKnownTypesSyntax3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WellKnownTypesSyntax3(WellKnownTypesSyntax3 other) : this() {
      _hasBits0 = other._hasBits0;
      a_ = other.a_;
      bg_ = other.bg_.Clone();
      floating_ = other.floating_;
      f18_ = other.f18_.Clone();
      F24 = other.F24;
      F25 = other.F25;
      F26 = other.F26;
      f5_ = other.f5_ != null ? other.f5_.Clone() : null;
      f4_ = other.f4_ != null ? other.f4_.Clone() : null;
      F3 = other.F3;
      F27 = other.F27;
      F28 = other.F28;
      f22_ = other.f22_ != null ? other.f22_.Clone() : null;
      f29_ = other.f29_;
      F2 = other.F2;
      f33_ = other.f33_ != null ? other.f33_.Clone() : null;
      f1_ = other.f1_ != null ? other.f1_.Clone() : null;
      F34 = other.F34;
      F35 = other.F35;
      f36_ = other.f36_ != null ? other.f36_.Clone() : null;
      f37_ = other.f37_ != null ? other.f37_.Clone() : null;
      f38_ = other.f38_ != null ? other.f38_.Clone() : null;
      f39_ = other.f39_ != null ? other.f39_.Clone() : null;
      f41_ = other.f41_ != null ? other.f41_.Clone() : null;
      f42_ = other.f42_ != null ? other.f42_.Clone() : null;
      f43_ = other.f43_ != null ? other.f43_.Clone() : null;
      f44_ = other.f44_ != null ? other.f44_.Clone() : null;
      f45_ = other.f45_;
      f46_ = other.f46_;
      f47_ = other.f47_ != null ? other.f47_.Clone() : null;
      f48_ = other.f48_ != null ? other.f48_.Clone() : null;
      f49_ = other.f49_ != null ? other.f49_.Clone() : null;
      f50_ = other.f50_;
      f9_ = other.f9_;
      f10_ = other.f10_ != null ? other.f10_.Clone() : null;
      f7_ = other.f7_ != null ? other.f7_.Clone() : null;
      f11_ = other.f11_;
      f20_ = other.f20_ != null ? other.f20_.Clone() : null;
      f13_ = other.f13_ != null ? other.f13_.Clone() : null;
      f12_ = other.f12_ != null ? other.f12_.Clone() : null;
      f6_ = other.f6_ != null ? other.f6_.Clone() : null;
      f14_ = other.f14_;
      f16_ = other.f16_ != null ? other.f16_.Clone() : null;
      f21_ = other.f21_.Clone();
      f8_ = other.f8_ != null ? other.f8_.Clone() : null;
      f15_ = other.f15_ != null ? other.f15_.Clone() : null;
      f17_ = other.f17_ != null ? other.f17_.Clone() : null;
      f19_ = other.f19_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WellKnownTypesSyntax3 Clone() {
      return new WellKnownTypesSyntax3(this);
    }

    /// <summary>Field number for the "a" field.</summary>
    public const int AFieldNumber = 100;
    private readonly static int ADefaultValue = 0;

    private int a_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int A {
      get { if ((_hasBits0 & 128) != 0) { return a_; } else { return ADefaultValue; } }
      set {
        _hasBits0 |= 128;
        a_ = value;
      }
    }
    /// <summary>Gets whether the "a" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasA {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "a" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearA() {
      _hasBits0 &= ~128;
    }

    /// <summary>Field number for the "bg" field.</summary>
    public const int BgFieldNumber = 101;
    private static readonly pb::FieldCodec<string> _repeated_bg_codec
        = pb::FieldCodec.ForString(810);
    private readonly pbc::RepeatedField<string> bg_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Bg {
      get { return bg_; }
    }

    /// <summary>Field number for the "floating" field.</summary>
    public const int FloatingFieldNumber = 102;
    private readonly static float FloatingDefaultValue = 0F;

    private float floating_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Floating {
      get { if ((_hasBits0 & 256) != 0) { return floating_; } else { return FloatingDefaultValue; } }
      set {
        _hasBits0 |= 256;
        floating_ = value;
      }
    }
    /// <summary>Gets whether the "floating" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFloating {
      get { return (_hasBits0 & 256) != 0; }
    }
    /// <summary>Clears the value of the "floating" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFloating() {
      _hasBits0 &= ~256;
    }

    /// <summary>Field number for the "f18" field.</summary>
    public const int F18FieldNumber = 18;
    private static readonly pb::FieldCodec<global::Google.Protobuf.WellKnownTypes.Any> _repeated_f18_codec
        = pb::FieldCodec.ForMessage(146, global::Google.Protobuf.WellKnownTypes.Any.Parser);
    private readonly pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any> f18_ = new pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any> F18 {
      get { return f18_; }
    }

    /// <summary>Field number for the "f24" field.</summary>
    public const int F24FieldNumber = 24;
    private static readonly pb::FieldCodec<bool?> _single_f24_codec = pb::FieldCodec.ForStructWrapper<bool>(194);
    private bool? f24_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool? F24 {
      get { return f24_; }
      set {
        f24_ = value;
      }
    }


    /// <summary>Field number for the "f25" field.</summary>
    public const int F25FieldNumber = 25;
    private static readonly pb::FieldCodec<pb::ByteString> _single_f25_codec = pb::FieldCodec.ForClassWrapper<pb::ByteString>(202);
    private pb::ByteString f25_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString F25 {
      get { return f25_; }
      set {
        f25_ = value;
      }
    }


    /// <summary>Field number for the "f26" field.</summary>
    public const int F26FieldNumber = 26;
    private static readonly pb::FieldCodec<double?> _single_f26_codec = pb::FieldCodec.ForStructWrapper<double>(210);
    private double? f26_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double? F26 {
      get { return f26_; }
      set {
        f26_ = value;
      }
    }


    /// <summary>Field number for the "f5" field.</summary>
    public const int F5FieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Duration f5_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Duration F5 {
      get { return f5_; }
      set {
        f5_ = value;
      }
    }

    /// <summary>Field number for the "f4" field.</summary>
    public const int F4FieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Empty f4_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Empty F4 {
      get { return f4_; }
      set {
        f4_ = value;
      }
    }

    /// <summary>Field number for the "f3" field.</summary>
    public const int F3FieldNumber = 3;
    private static readonly pb::FieldCodec<float?> _single_f3_codec = pb::FieldCodec.ForStructWrapper<float>(26);
    private float? f3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float? F3 {
      get { return f3_; }
      set {
        f3_ = value;
      }
    }


    /// <summary>Field number for the "f27" field.</summary>
    public const int F27FieldNumber = 27;
    private static readonly pb::FieldCodec<int?> _single_f27_codec = pb::FieldCodec.ForStructWrapper<int>(218);
    private int? f27_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int? F27 {
      get { return f27_; }
      set {
        f27_ = value;
      }
    }


    /// <summary>Field number for the "f28" field.</summary>
    public const int F28FieldNumber = 28;
    private static readonly pb::FieldCodec<long?> _single_f28_codec = pb::FieldCodec.ForStructWrapper<long>(226);
    private long? f28_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long? F28 {
      get { return f28_; }
      set {
        f28_ = value;
      }
    }


    /// <summary>Field number for the "f22" field.</summary>
    public const int F22FieldNumber = 22;
    private global::Google.Protobuf.WellKnownTypes.ListValue f22_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.ListValue F22 {
      get { return f22_; }
      set {
        f22_ = value;
      }
    }

    /// <summary>Field number for the "f29" field.</summary>
    public const int F29FieldNumber = 29;
    private readonly static global::Google.Protobuf.WellKnownTypes.NullValue F29DefaultValue = global::Google.Protobuf.WellKnownTypes.NullValue.NullValue;

    private global::Google.Protobuf.WellKnownTypes.NullValue f29_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.NullValue F29 {
      get { if ((_hasBits0 & 8) != 0) { return f29_; } else { return F29DefaultValue; } }
      set {
        _hasBits0 |= 8;
        f29_ = value;
      }
    }
    /// <summary>Gets whether the "f29" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasF29 {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "f29" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearF29() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "f2" field.</summary>
    public const int F2FieldNumber = 2;
    private static readonly pb::FieldCodec<string> _single_f2_codec = pb::FieldCodec.ForClassWrapper<string>(18);
    private string f2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string F2 {
      get { return f2_; }
      set {
        f2_ = value;
      }
    }


    /// <summary>Field number for the "f33" field.</summary>
    public const int F33FieldNumber = 33;
    private global::Google.Protobuf.WellKnownTypes.Struct f33_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Struct F33 {
      get { return f33_; }
      set {
        f33_ = value;
      }
    }

    /// <summary>Field number for the "f1" field.</summary>
    public const int F1FieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp f1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp F1 {
      get { return f1_; }
      set {
        f1_ = value;
      }
    }

    /// <summary>Field number for the "f34" field.</summary>
    public const int F34FieldNumber = 34;
    private static readonly pb::FieldCodec<uint?> _single_f34_codec = pb::FieldCodec.ForStructWrapper<uint>(274);
    private uint? f34_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint? F34 {
      get { return f34_; }
      set {
        f34_ = value;
      }
    }


    /// <summary>Field number for the "f35" field.</summary>
    public const int F35FieldNumber = 35;
    private static readonly pb::FieldCodec<ulong?> _single_f35_codec = pb::FieldCodec.ForStructWrapper<ulong>(282);
    private ulong? f35_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong? F35 {
      get { return f35_; }
      set {
        f35_ = value;
      }
    }


    /// <summary>Field number for the "f36" field.</summary>
    public const int F36FieldNumber = 36;
    private global::Google.Protobuf.WellKnownTypes.Value f36_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Value F36 {
      get { return f36_; }
      set {
        f36_ = value;
      }
    }

    /// <summary>Field number for the "f37" field.</summary>
    public const int F37FieldNumber = 37;
    private global::Google.Protobuf.WellKnownTypes.Api f37_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Api F37 {
      get { return f37_; }
      set {
        f37_ = value;
      }
    }

    /// <summary>Field number for the "f38" field.</summary>
    public const int F38FieldNumber = 38;
    private global::Google.Protobuf.WellKnownTypes.FieldMask f38_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.FieldMask F38 {
      get { return f38_; }
      set {
        f38_ = value;
      }
    }

    /// <summary>Field number for the "f39" field.</summary>
    public const int F39FieldNumber = 39;
    private global::Google.Protobuf.WellKnownTypes.SourceContext f39_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.SourceContext F39 {
      get { return f39_; }
      set {
        f39_ = value;
      }
    }

    /// <summary>Field number for the "f41" field.</summary>
    public const int F41FieldNumber = 41;
    private global::Google.Protobuf.WellKnownTypes.Type f41_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Type F41 {
      get { return f41_; }
      set {
        f41_ = value;
      }
    }

    /// <summary>Field number for the "f42" field.</summary>
    public const int F42FieldNumber = 42;
    private global::Google.Protobuf.WellKnownTypes.Enum f42_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Enum F42 {
      get { return f42_; }
      set {
        f42_ = value;
      }
    }

    /// <summary>Field number for the "f43" field.</summary>
    public const int F43FieldNumber = 43;
    private global::Google.Protobuf.WellKnownTypes.EnumValue f43_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.EnumValue F43 {
      get { return f43_; }
      set {
        f43_ = value;
      }
    }

    /// <summary>Field number for the "f44" field.</summary>
    public const int F44FieldNumber = 44;
    private global::Google.Protobuf.WellKnownTypes.Field f44_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Field F44 {
      get { return f44_; }
      set {
        f44_ = value;
      }
    }

    /// <summary>Field number for the "f45" field.</summary>
    public const int F45FieldNumber = 45;
    private readonly static global::Google.Protobuf.WellKnownTypes.Field.Types.Cardinality F45DefaultValue = global::Google.Protobuf.WellKnownTypes.Field.Types.Cardinality.Unknown;

    private global::Google.Protobuf.WellKnownTypes.Field.Types.Cardinality f45_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Field.Types.Cardinality F45 {
      get { if ((_hasBits0 & 16) != 0) { return f45_; } else { return F45DefaultValue; } }
      set {
        _hasBits0 |= 16;
        f45_ = value;
      }
    }
    /// <summary>Gets whether the "f45" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasF45 {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "f45" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearF45() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "f46" field.</summary>
    public const int F46FieldNumber = 46;
    private readonly static global::Google.Protobuf.WellKnownTypes.Field.Types.Kind F46DefaultValue = global::Google.Protobuf.WellKnownTypes.Field.Types.Kind.TypeUnknown;

    private global::Google.Protobuf.WellKnownTypes.Field.Types.Kind f46_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Field.Types.Kind F46 {
      get { if ((_hasBits0 & 32) != 0) { return f46_; } else { return F46DefaultValue; } }
      set {
        _hasBits0 |= 32;
        f46_ = value;
      }
    }
    /// <summary>Gets whether the "f46" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasF46 {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "f46" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearF46() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "f47" field.</summary>
    public const int F47FieldNumber = 47;
    private global::Google.Protobuf.WellKnownTypes.Method f47_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Method F47 {
      get { return f47_; }
      set {
        f47_ = value;
      }
    }

    /// <summary>Field number for the "f48" field.</summary>
    public const int F48FieldNumber = 48;
    private global::Google.Protobuf.WellKnownTypes.Mixin f48_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Mixin F48 {
      get { return f48_; }
      set {
        f48_ = value;
      }
    }

    /// <summary>Field number for the "f49" field.</summary>
    public const int F49FieldNumber = 49;
    private global::Google.Protobuf.WellKnownTypes.Option f49_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Option F49 {
      get { return f49_; }
      set {
        f49_ = value;
      }
    }

    /// <summary>Field number for the "f50" field.</summary>
    public const int F50FieldNumber = 50;
    private readonly static global::Google.Protobuf.WellKnownTypes.Syntax F50DefaultValue = global::Google.Protobuf.WellKnownTypes.Syntax.Proto2;

    private global::Google.Protobuf.WellKnownTypes.Syntax f50_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Syntax F50 {
      get { if ((_hasBits0 & 64) != 0) { return f50_; } else { return F50DefaultValue; } }
      set {
        _hasBits0 |= 64;
        f50_ = value;
      }
    }
    /// <summary>Gets whether the "f50" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasF50 {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "f50" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearF50() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "f9" field.</summary>
    public const int F9FieldNumber = 9;
    private readonly static global::Google.Type.CalendarPeriod F9DefaultValue = global::Google.Type.CalendarPeriod.Unspecified;

    private global::Google.Type.CalendarPeriod f9_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.CalendarPeriod F9 {
      get { if ((_hasBits0 & 1) != 0) { return f9_; } else { return F9DefaultValue; } }
      set {
        _hasBits0 |= 1;
        f9_ = value;
      }
    }
    /// <summary>Gets whether the "f9" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasF9 {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "f9" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearF9() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "f10" field.</summary>
    public const int F10FieldNumber = 10;
    private global::Google.Type.Color f10_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.Color F10 {
      get { return f10_; }
      set {
        f10_ = value;
      }
    }

    /// <summary>Field number for the "f7" field.</summary>
    public const int F7FieldNumber = 7;
    private global::Google.Type.Date f7_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.Date F7 {
      get { return f7_; }
      set {
        f7_ = value;
      }
    }

    /// <summary>Field number for the "f11" field.</summary>
    public const int F11FieldNumber = 11;
    private readonly static global::Google.Type.DayOfWeek F11DefaultValue = global::Google.Type.DayOfWeek.Unspecified;

    private global::Google.Type.DayOfWeek f11_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.DayOfWeek F11 {
      get { if ((_hasBits0 & 2) != 0) { return f11_; } else { return F11DefaultValue; } }
      set {
        _hasBits0 |= 2;
        f11_ = value;
      }
    }
    /// <summary>Gets whether the "f11" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasF11 {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "f11" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearF11() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "f20" field.</summary>
    public const int F20FieldNumber = 20;
    private global::Google.Type.Expr f20_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.Expr F20 {
      get { return f20_; }
      set {
        f20_ = value;
      }
    }

    /// <summary>Field number for the "f13" field.</summary>
    public const int F13FieldNumber = 13;
    private global::Google.Type.Fraction f13_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.Fraction F13 {
      get { return f13_; }
      set {
        f13_ = value;
      }
    }

    /// <summary>Field number for the "f12" field.</summary>
    public const int F12FieldNumber = 12;
    private global::Google.Type.LatLng f12_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.LatLng F12 {
      get { return f12_; }
      set {
        f12_ = value;
      }
    }

    /// <summary>Field number for the "f6" field.</summary>
    public const int F6FieldNumber = 6;
    private global::Google.Type.Money f6_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.Money F6 {
      get { return f6_; }
      set {
        f6_ = value;
      }
    }

    /// <summary>Field number for the "f14" field.</summary>
    public const int F14FieldNumber = 14;
    private readonly static global::Google.Type.Month F14DefaultValue = global::Google.Type.Month.Unspecified;

    private global::Google.Type.Month f14_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.Month F14 {
      get { if ((_hasBits0 & 4) != 0) { return f14_; } else { return F14DefaultValue; } }
      set {
        _hasBits0 |= 4;
        f14_ = value;
      }
    }
    /// <summary>Gets whether the "f14" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasF14 {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "f14" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearF14() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "f16" field.</summary>
    public const int F16FieldNumber = 16;
    private global::Google.Type.PostalAddress f16_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.PostalAddress F16 {
      get { return f16_; }
      set {
        f16_ = value;
      }
    }

    /// <summary>Field number for the "f21" field.</summary>
    public const int F21FieldNumber = 21;
    private static readonly pb::FieldCodec<global::Google.Type.Quaternion> _repeated_f21_codec
        = pb::FieldCodec.ForMessage(170, global::Google.Type.Quaternion.Parser);
    private readonly pbc::RepeatedField<global::Google.Type.Quaternion> f21_ = new pbc::RepeatedField<global::Google.Type.Quaternion>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Type.Quaternion> F21 {
      get { return f21_; }
    }

    /// <summary>Field number for the "f8" field.</summary>
    public const int F8FieldNumber = 8;
    private global::Google.Type.TimeOfDay f8_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.TimeOfDay F8 {
      get { return f8_; }
      set {
        f8_ = value;
      }
    }

    /// <summary>Field number for the "f15" field.</summary>
    public const int F15FieldNumber = 15;
    private global::Google.Type.PhoneNumber f15_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.PhoneNumber F15 {
      get { return f15_; }
      set {
        f15_ = value;
      }
    }

    /// <summary>Field number for the "f17" field.</summary>
    public const int F17FieldNumber = 17;
    private global::Google.Type.LocalizedText f17_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.LocalizedText F17 {
      get { return f17_; }
      set {
        f17_ = value;
      }
    }

    /// <summary>Field number for the "f19" field.</summary>
    public const int F19FieldNumber = 19;
    private static readonly pb::FieldCodec<global::Google.Type.Interval> _repeated_f19_codec
        = pb::FieldCodec.ForMessage(154, global::Google.Type.Interval.Parser);
    private readonly pbc::RepeatedField<global::Google.Type.Interval> f19_ = new pbc::RepeatedField<global::Google.Type.Interval>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Type.Interval> F19 {
      get { return f19_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WellKnownTypesSyntax3);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WellKnownTypesSyntax3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (A != other.A) return false;
      if(!bg_.Equals(other.bg_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Floating, other.Floating)) return false;
      if(!f18_.Equals(other.f18_)) return false;
      if (F24 != other.F24) return false;
      if (F25 != other.F25) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableDoubleEqualityComparer.Equals(F26, other.F26)) return false;
      if (!object.Equals(F5, other.F5)) return false;
      if (!object.Equals(F4, other.F4)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.Equals(F3, other.F3)) return false;
      if (F27 != other.F27) return false;
      if (F28 != other.F28) return false;
      if (!object.Equals(F22, other.F22)) return false;
      if (F29 != other.F29) return false;
      if (F2 != other.F2) return false;
      if (!object.Equals(F33, other.F33)) return false;
      if (!object.Equals(F1, other.F1)) return false;
      if (F34 != other.F34) return false;
      if (F35 != other.F35) return false;
      if (!object.Equals(F36, other.F36)) return false;
      if (!object.Equals(F37, other.F37)) return false;
      if (!object.Equals(F38, other.F38)) return false;
      if (!object.Equals(F39, other.F39)) return false;
      if (!object.Equals(F41, other.F41)) return false;
      if (!object.Equals(F42, other.F42)) return false;
      if (!object.Equals(F43, other.F43)) return false;
      if (!object.Equals(F44, other.F44)) return false;
      if (F45 != other.F45) return false;
      if (F46 != other.F46) return false;
      if (!object.Equals(F47, other.F47)) return false;
      if (!object.Equals(F48, other.F48)) return false;
      if (!object.Equals(F49, other.F49)) return false;
      if (F50 != other.F50) return false;
      if (F9 != other.F9) return false;
      if (!object.Equals(F10, other.F10)) return false;
      if (!object.Equals(F7, other.F7)) return false;
      if (F11 != other.F11) return false;
      if (!object.Equals(F20, other.F20)) return false;
      if (!object.Equals(F13, other.F13)) return false;
      if (!object.Equals(F12, other.F12)) return false;
      if (!object.Equals(F6, other.F6)) return false;
      if (F14 != other.F14) return false;
      if (!object.Equals(F16, other.F16)) return false;
      if(!f21_.Equals(other.f21_)) return false;
      if (!object.Equals(F8, other.F8)) return false;
      if (!object.Equals(F15, other.F15)) return false;
      if (!object.Equals(F17, other.F17)) return false;
      if(!f19_.Equals(other.f19_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasA) hash ^= A.GetHashCode();
      hash ^= bg_.GetHashCode();
      if (HasFloating) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Floating);
      hash ^= f18_.GetHashCode();
      if (f24_ != null) hash ^= F24.GetHashCode();
      if (f25_ != null) hash ^= F25.GetHashCode();
      if (f26_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableDoubleEqualityComparer.GetHashCode(F26);
      if (f5_ != null) hash ^= F5.GetHashCode();
      if (f4_ != null) hash ^= F4.GetHashCode();
      if (f3_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.GetHashCode(F3);
      if (f27_ != null) hash ^= F27.GetHashCode();
      if (f28_ != null) hash ^= F28.GetHashCode();
      if (f22_ != null) hash ^= F22.GetHashCode();
      if (HasF29) hash ^= F29.GetHashCode();
      if (f2_ != null) hash ^= F2.GetHashCode();
      if (f33_ != null) hash ^= F33.GetHashCode();
      if (f1_ != null) hash ^= F1.GetHashCode();
      if (f34_ != null) hash ^= F34.GetHashCode();
      if (f35_ != null) hash ^= F35.GetHashCode();
      if (f36_ != null) hash ^= F36.GetHashCode();
      if (f37_ != null) hash ^= F37.GetHashCode();
      if (f38_ != null) hash ^= F38.GetHashCode();
      if (f39_ != null) hash ^= F39.GetHashCode();
      if (f41_ != null) hash ^= F41.GetHashCode();
      if (f42_ != null) hash ^= F42.GetHashCode();
      if (f43_ != null) hash ^= F43.GetHashCode();
      if (f44_ != null) hash ^= F44.GetHashCode();
      if (HasF45) hash ^= F45.GetHashCode();
      if (HasF46) hash ^= F46.GetHashCode();
      if (f47_ != null) hash ^= F47.GetHashCode();
      if (f48_ != null) hash ^= F48.GetHashCode();
      if (f49_ != null) hash ^= F49.GetHashCode();
      if (HasF50) hash ^= F50.GetHashCode();
      if (HasF9) hash ^= F9.GetHashCode();
      if (f10_ != null) hash ^= F10.GetHashCode();
      if (f7_ != null) hash ^= F7.GetHashCode();
      if (HasF11) hash ^= F11.GetHashCode();
      if (f20_ != null) hash ^= F20.GetHashCode();
      if (f13_ != null) hash ^= F13.GetHashCode();
      if (f12_ != null) hash ^= F12.GetHashCode();
      if (f6_ != null) hash ^= F6.GetHashCode();
      if (HasF14) hash ^= F14.GetHashCode();
      if (f16_ != null) hash ^= F16.GetHashCode();
      hash ^= f21_.GetHashCode();
      if (f8_ != null) hash ^= F8.GetHashCode();
      if (f15_ != null) hash ^= F15.GetHashCode();
      if (f17_ != null) hash ^= F17.GetHashCode();
      hash ^= f19_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (f1_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(F1);
      }
      if (f2_ != null) {
        _single_f2_codec.WriteTagAndValue(output, F2);
      }
      if (f3_ != null) {
        _single_f3_codec.WriteTagAndValue(output, F3);
      }
      if (f4_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(F4);
      }
      if (f5_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(F5);
      }
      if (f6_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(F6);
      }
      if (f7_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(F7);
      }
      if (f8_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(F8);
      }
      if (HasF9) {
        output.WriteRawTag(72);
        output.WriteEnum((int) F9);
      }
      if (f10_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(F10);
      }
      if (HasF11) {
        output.WriteRawTag(88);
        output.WriteEnum((int) F11);
      }
      if (f12_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(F12);
      }
      if (f13_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(F13);
      }
      if (HasF14) {
        output.WriteRawTag(112);
        output.WriteEnum((int) F14);
      }
      if (f15_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(F15);
      }
      if (f16_ != null) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(F16);
      }
      if (f17_ != null) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(F17);
      }
      f18_.WriteTo(output, _repeated_f18_codec);
      f19_.WriteTo(output, _repeated_f19_codec);
      if (f20_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(F20);
      }
      f21_.WriteTo(output, _repeated_f21_codec);
      if (f22_ != null) {
        output.WriteRawTag(178, 1);
        output.WriteMessage(F22);
      }
      if (f24_ != null) {
        _single_f24_codec.WriteTagAndValue(output, F24);
      }
      if (f25_ != null) {
        _single_f25_codec.WriteTagAndValue(output, F25);
      }
      if (f26_ != null) {
        _single_f26_codec.WriteTagAndValue(output, F26);
      }
      if (f27_ != null) {
        _single_f27_codec.WriteTagAndValue(output, F27);
      }
      if (f28_ != null) {
        _single_f28_codec.WriteTagAndValue(output, F28);
      }
      if (HasF29) {
        output.WriteRawTag(232, 1);
        output.WriteEnum((int) F29);
      }
      if (f33_ != null) {
        output.WriteRawTag(138, 2);
        output.WriteMessage(F33);
      }
      if (f34_ != null) {
        _single_f34_codec.WriteTagAndValue(output, F34);
      }
      if (f35_ != null) {
        _single_f35_codec.WriteTagAndValue(output, F35);
      }
      if (f36_ != null) {
        output.WriteRawTag(162, 2);
        output.WriteMessage(F36);
      }
      if (f37_ != null) {
        output.WriteRawTag(170, 2);
        output.WriteMessage(F37);
      }
      if (f38_ != null) {
        output.WriteRawTag(178, 2);
        output.WriteMessage(F38);
      }
      if (f39_ != null) {
        output.WriteRawTag(186, 2);
        output.WriteMessage(F39);
      }
      if (f41_ != null) {
        output.WriteRawTag(202, 2);
        output.WriteMessage(F41);
      }
      if (f42_ != null) {
        output.WriteRawTag(210, 2);
        output.WriteMessage(F42);
      }
      if (f43_ != null) {
        output.WriteRawTag(218, 2);
        output.WriteMessage(F43);
      }
      if (f44_ != null) {
        output.WriteRawTag(226, 2);
        output.WriteMessage(F44);
      }
      if (HasF45) {
        output.WriteRawTag(232, 2);
        output.WriteEnum((int) F45);
      }
      if (HasF46) {
        output.WriteRawTag(240, 2);
        output.WriteEnum((int) F46);
      }
      if (f47_ != null) {
        output.WriteRawTag(250, 2);
        output.WriteMessage(F47);
      }
      if (f48_ != null) {
        output.WriteRawTag(130, 3);
        output.WriteMessage(F48);
      }
      if (f49_ != null) {
        output.WriteRawTag(138, 3);
        output.WriteMessage(F49);
      }
      if (HasF50) {
        output.WriteRawTag(144, 3);
        output.WriteEnum((int) F50);
      }
      if (HasA) {
        output.WriteRawTag(160, 6);
        output.WriteInt32(A);
      }
      bg_.WriteTo(output, _repeated_bg_codec);
      if (HasFloating) {
        output.WriteRawTag(181, 6);
        output.WriteFloat(Floating);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (f1_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(F1);
      }
      if (f2_ != null) {
        _single_f2_codec.WriteTagAndValue(ref output, F2);
      }
      if (f3_ != null) {
        _single_f3_codec.WriteTagAndValue(ref output, F3);
      }
      if (f4_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(F4);
      }
      if (f5_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(F5);
      }
      if (f6_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(F6);
      }
      if (f7_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(F7);
      }
      if (f8_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(F8);
      }
      if (HasF9) {
        output.WriteRawTag(72);
        output.WriteEnum((int) F9);
      }
      if (f10_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(F10);
      }
      if (HasF11) {
        output.WriteRawTag(88);
        output.WriteEnum((int) F11);
      }
      if (f12_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(F12);
      }
      if (f13_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(F13);
      }
      if (HasF14) {
        output.WriteRawTag(112);
        output.WriteEnum((int) F14);
      }
      if (f15_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(F15);
      }
      if (f16_ != null) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(F16);
      }
      if (f17_ != null) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(F17);
      }
      f18_.WriteTo(ref output, _repeated_f18_codec);
      f19_.WriteTo(ref output, _repeated_f19_codec);
      if (f20_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(F20);
      }
      f21_.WriteTo(ref output, _repeated_f21_codec);
      if (f22_ != null) {
        output.WriteRawTag(178, 1);
        output.WriteMessage(F22);
      }
      if (f24_ != null) {
        _single_f24_codec.WriteTagAndValue(ref output, F24);
      }
      if (f25_ != null) {
        _single_f25_codec.WriteTagAndValue(ref output, F25);
      }
      if (f26_ != null) {
        _single_f26_codec.WriteTagAndValue(ref output, F26);
      }
      if (f27_ != null) {
        _single_f27_codec.WriteTagAndValue(ref output, F27);
      }
      if (f28_ != null) {
        _single_f28_codec.WriteTagAndValue(ref output, F28);
      }
      if (HasF29) {
        output.WriteRawTag(232, 1);
        output.WriteEnum((int) F29);
      }
      if (f33_ != null) {
        output.WriteRawTag(138, 2);
        output.WriteMessage(F33);
      }
      if (f34_ != null) {
        _single_f34_codec.WriteTagAndValue(ref output, F34);
      }
      if (f35_ != null) {
        _single_f35_codec.WriteTagAndValue(ref output, F35);
      }
      if (f36_ != null) {
        output.WriteRawTag(162, 2);
        output.WriteMessage(F36);
      }
      if (f37_ != null) {
        output.WriteRawTag(170, 2);
        output.WriteMessage(F37);
      }
      if (f38_ != null) {
        output.WriteRawTag(178, 2);
        output.WriteMessage(F38);
      }
      if (f39_ != null) {
        output.WriteRawTag(186, 2);
        output.WriteMessage(F39);
      }
      if (f41_ != null) {
        output.WriteRawTag(202, 2);
        output.WriteMessage(F41);
      }
      if (f42_ != null) {
        output.WriteRawTag(210, 2);
        output.WriteMessage(F42);
      }
      if (f43_ != null) {
        output.WriteRawTag(218, 2);
        output.WriteMessage(F43);
      }
      if (f44_ != null) {
        output.WriteRawTag(226, 2);
        output.WriteMessage(F44);
      }
      if (HasF45) {
        output.WriteRawTag(232, 2);
        output.WriteEnum((int) F45);
      }
      if (HasF46) {
        output.WriteRawTag(240, 2);
        output.WriteEnum((int) F46);
      }
      if (f47_ != null) {
        output.WriteRawTag(250, 2);
        output.WriteMessage(F47);
      }
      if (f48_ != null) {
        output.WriteRawTag(130, 3);
        output.WriteMessage(F48);
      }
      if (f49_ != null) {
        output.WriteRawTag(138, 3);
        output.WriteMessage(F49);
      }
      if (HasF50) {
        output.WriteRawTag(144, 3);
        output.WriteEnum((int) F50);
      }
      if (HasA) {
        output.WriteRawTag(160, 6);
        output.WriteInt32(A);
      }
      bg_.WriteTo(ref output, _repeated_bg_codec);
      if (HasFloating) {
        output.WriteRawTag(181, 6);
        output.WriteFloat(Floating);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasA) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(A);
      }
      size += bg_.CalculateSize(_repeated_bg_codec);
      if (HasFloating) {
        size += 2 + 4;
      }
      size += f18_.CalculateSize(_repeated_f18_codec);
      if (f24_ != null) {
        size += _single_f24_codec.CalculateSizeWithTag(F24);
      }
      if (f25_ != null) {
        size += _single_f25_codec.CalculateSizeWithTag(F25);
      }
      if (f26_ != null) {
        size += _single_f26_codec.CalculateSizeWithTag(F26);
      }
      if (f5_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(F5);
      }
      if (f4_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(F4);
      }
      if (f3_ != null) {
        size += _single_f3_codec.CalculateSizeWithTag(F3);
      }
      if (f27_ != null) {
        size += _single_f27_codec.CalculateSizeWithTag(F27);
      }
      if (f28_ != null) {
        size += _single_f28_codec.CalculateSizeWithTag(F28);
      }
      if (f22_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(F22);
      }
      if (HasF29) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) F29);
      }
      if (f2_ != null) {
        size += _single_f2_codec.CalculateSizeWithTag(F2);
      }
      if (f33_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(F33);
      }
      if (f1_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(F1);
      }
      if (f34_ != null) {
        size += _single_f34_codec.CalculateSizeWithTag(F34);
      }
      if (f35_ != null) {
        size += _single_f35_codec.CalculateSizeWithTag(F35);
      }
      if (f36_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(F36);
      }
      if (f37_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(F37);
      }
      if (f38_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(F38);
      }
      if (f39_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(F39);
      }
      if (f41_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(F41);
      }
      if (f42_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(F42);
      }
      if (f43_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(F43);
      }
      if (f44_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(F44);
      }
      if (HasF45) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) F45);
      }
      if (HasF46) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) F46);
      }
      if (f47_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(F47);
      }
      if (f48_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(F48);
      }
      if (f49_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(F49);
      }
      if (HasF50) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) F50);
      }
      if (HasF9) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) F9);
      }
      if (f10_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(F10);
      }
      if (f7_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(F7);
      }
      if (HasF11) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) F11);
      }
      if (f20_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(F20);
      }
      if (f13_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(F13);
      }
      if (f12_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(F12);
      }
      if (f6_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(F6);
      }
      if (HasF14) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) F14);
      }
      if (f16_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(F16);
      }
      size += f21_.CalculateSize(_repeated_f21_codec);
      if (f8_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(F8);
      }
      if (f15_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(F15);
      }
      if (f17_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(F17);
      }
      size += f19_.CalculateSize(_repeated_f19_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WellKnownTypesSyntax3 other) {
      if (other == null) {
        return;
      }
      if (other.HasA) {
        A = other.A;
      }
      bg_.Add(other.bg_);
      if (other.HasFloating) {
        Floating = other.Floating;
      }
      f18_.Add(other.f18_);
      if (other.f24_ != null) {
        if (f24_ == null || other.F24 != false) {
          F24 = other.F24;
        }
      }
      if (other.f25_ != null) {
        if (f25_ == null || other.F25 != pb::ByteString.Empty) {
          F25 = other.F25;
        }
      }
      if (other.f26_ != null) {
        if (f26_ == null || other.F26 != 0D) {
          F26 = other.F26;
        }
      }
      if (other.f5_ != null) {
        if (f5_ == null) {
          F5 = new global::Google.Protobuf.WellKnownTypes.Duration();
        }
        F5.MergeFrom(other.F5);
      }
      if (other.f4_ != null) {
        if (f4_ == null) {
          F4 = new global::Google.Protobuf.WellKnownTypes.Empty();
        }
        F4.MergeFrom(other.F4);
      }
      if (other.f3_ != null) {
        if (f3_ == null || other.F3 != 0F) {
          F3 = other.F3;
        }
      }
      if (other.f27_ != null) {
        if (f27_ == null || other.F27 != 0) {
          F27 = other.F27;
        }
      }
      if (other.f28_ != null) {
        if (f28_ == null || other.F28 != 0L) {
          F28 = other.F28;
        }
      }
      if (other.f22_ != null) {
        if (f22_ == null) {
          F22 = new global::Google.Protobuf.WellKnownTypes.ListValue();
        }
        F22.MergeFrom(other.F22);
      }
      if (other.HasF29) {
        F29 = other.F29;
      }
      if (other.f2_ != null) {
        if (f2_ == null || other.F2 != "") {
          F2 = other.F2;
        }
      }
      if (other.f33_ != null) {
        if (f33_ == null) {
          F33 = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        F33.MergeFrom(other.F33);
      }
      if (other.f1_ != null) {
        if (f1_ == null) {
          F1 = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        F1.MergeFrom(other.F1);
      }
      if (other.f34_ != null) {
        if (f34_ == null || other.F34 != 0) {
          F34 = other.F34;
        }
      }
      if (other.f35_ != null) {
        if (f35_ == null || other.F35 != 0UL) {
          F35 = other.F35;
        }
      }
      if (other.f36_ != null) {
        if (f36_ == null) {
          F36 = new global::Google.Protobuf.WellKnownTypes.Value();
        }
        F36.MergeFrom(other.F36);
      }
      if (other.f37_ != null) {
        if (f37_ == null) {
          F37 = new global::Google.Protobuf.WellKnownTypes.Api();
        }
        F37.MergeFrom(other.F37);
      }
      if (other.f38_ != null) {
        if (f38_ == null) {
          F38 = new global::Google.Protobuf.WellKnownTypes.FieldMask();
        }
        F38.MergeFrom(other.F38);
      }
      if (other.f39_ != null) {
        if (f39_ == null) {
          F39 = new global::Google.Protobuf.WellKnownTypes.SourceContext();
        }
        F39.MergeFrom(other.F39);
      }
      if (other.f41_ != null) {
        if (f41_ == null) {
          F41 = new global::Google.Protobuf.WellKnownTypes.Type();
        }
        F41.MergeFrom(other.F41);
      }
      if (other.f42_ != null) {
        if (f42_ == null) {
          F42 = new global::Google.Protobuf.WellKnownTypes.Enum();
        }
        F42.MergeFrom(other.F42);
      }
      if (other.f43_ != null) {
        if (f43_ == null) {
          F43 = new global::Google.Protobuf.WellKnownTypes.EnumValue();
        }
        F43.MergeFrom(other.F43);
      }
      if (other.f44_ != null) {
        if (f44_ == null) {
          F44 = new global::Google.Protobuf.WellKnownTypes.Field();
        }
        F44.MergeFrom(other.F44);
      }
      if (other.HasF45) {
        F45 = other.F45;
      }
      if (other.HasF46) {
        F46 = other.F46;
      }
      if (other.f47_ != null) {
        if (f47_ == null) {
          F47 = new global::Google.Protobuf.WellKnownTypes.Method();
        }
        F47.MergeFrom(other.F47);
      }
      if (other.f48_ != null) {
        if (f48_ == null) {
          F48 = new global::Google.Protobuf.WellKnownTypes.Mixin();
        }
        F48.MergeFrom(other.F48);
      }
      if (other.f49_ != null) {
        if (f49_ == null) {
          F49 = new global::Google.Protobuf.WellKnownTypes.Option();
        }
        F49.MergeFrom(other.F49);
      }
      if (other.HasF50) {
        F50 = other.F50;
      }
      if (other.HasF9) {
        F9 = other.F9;
      }
      if (other.f10_ != null) {
        if (f10_ == null) {
          F10 = new global::Google.Type.Color();
        }
        F10.MergeFrom(other.F10);
      }
      if (other.f7_ != null) {
        if (f7_ == null) {
          F7 = new global::Google.Type.Date();
        }
        F7.MergeFrom(other.F7);
      }
      if (other.HasF11) {
        F11 = other.F11;
      }
      if (other.f20_ != null) {
        if (f20_ == null) {
          F20 = new global::Google.Type.Expr();
        }
        F20.MergeFrom(other.F20);
      }
      if (other.f13_ != null) {
        if (f13_ == null) {
          F13 = new global::Google.Type.Fraction();
        }
        F13.MergeFrom(other.F13);
      }
      if (other.f12_ != null) {
        if (f12_ == null) {
          F12 = new global::Google.Type.LatLng();
        }
        F12.MergeFrom(other.F12);
      }
      if (other.f6_ != null) {
        if (f6_ == null) {
          F6 = new global::Google.Type.Money();
        }
        F6.MergeFrom(other.F6);
      }
      if (other.HasF14) {
        F14 = other.F14;
      }
      if (other.f16_ != null) {
        if (f16_ == null) {
          F16 = new global::Google.Type.PostalAddress();
        }
        F16.MergeFrom(other.F16);
      }
      f21_.Add(other.f21_);
      if (other.f8_ != null) {
        if (f8_ == null) {
          F8 = new global::Google.Type.TimeOfDay();
        }
        F8.MergeFrom(other.F8);
      }
      if (other.f15_ != null) {
        if (f15_ == null) {
          F15 = new global::Google.Type.PhoneNumber();
        }
        F15.MergeFrom(other.F15);
      }
      if (other.f17_ != null) {
        if (f17_ == null) {
          F17 = new global::Google.Type.LocalizedText();
        }
        F17.MergeFrom(other.F17);
      }
      f19_.Add(other.f19_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (f1_ == null) {
              F1 = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(F1);
            break;
          }
          case 18: {
            string value = _single_f2_codec.Read(input);
            if (f2_ == null || value != "") {
              F2 = value;
            }
            break;
          }
          case 26: {
            float? value = _single_f3_codec.Read(input);
            if (f3_ == null || value != 0F) {
              F3 = value;
            }
            break;
          }
          case 34: {
            if (f4_ == null) {
              F4 = new global::Google.Protobuf.WellKnownTypes.Empty();
            }
            input.ReadMessage(F4);
            break;
          }
          case 42: {
            if (f5_ == null) {
              F5 = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(F5);
            break;
          }
          case 50: {
            if (f6_ == null) {
              F6 = new global::Google.Type.Money();
            }
            input.ReadMessage(F6);
            break;
          }
          case 58: {
            if (f7_ == null) {
              F7 = new global::Google.Type.Date();
            }
            input.ReadMessage(F7);
            break;
          }
          case 66: {
            if (f8_ == null) {
              F8 = new global::Google.Type.TimeOfDay();
            }
            input.ReadMessage(F8);
            break;
          }
          case 72: {
            F9 = (global::Google.Type.CalendarPeriod) input.ReadEnum();
            break;
          }
          case 82: {
            if (f10_ == null) {
              F10 = new global::Google.Type.Color();
            }
            input.ReadMessage(F10);
            break;
          }
          case 88: {
            F11 = (global::Google.Type.DayOfWeek) input.ReadEnum();
            break;
          }
          case 98: {
            if (f12_ == null) {
              F12 = new global::Google.Type.LatLng();
            }
            input.ReadMessage(F12);
            break;
          }
          case 106: {
            if (f13_ == null) {
              F13 = new global::Google.Type.Fraction();
            }
            input.ReadMessage(F13);
            break;
          }
          case 112: {
            F14 = (global::Google.Type.Month) input.ReadEnum();
            break;
          }
          case 122: {
            if (f15_ == null) {
              F15 = new global::Google.Type.PhoneNumber();
            }
            input.ReadMessage(F15);
            break;
          }
          case 130: {
            if (f16_ == null) {
              F16 = new global::Google.Type.PostalAddress();
            }
            input.ReadMessage(F16);
            break;
          }
          case 138: {
            if (f17_ == null) {
              F17 = new global::Google.Type.LocalizedText();
            }
            input.ReadMessage(F17);
            break;
          }
          case 146: {
            f18_.AddEntriesFrom(input, _repeated_f18_codec);
            break;
          }
          case 154: {
            f19_.AddEntriesFrom(input, _repeated_f19_codec);
            break;
          }
          case 162: {
            if (f20_ == null) {
              F20 = new global::Google.Type.Expr();
            }
            input.ReadMessage(F20);
            break;
          }
          case 170: {
            f21_.AddEntriesFrom(input, _repeated_f21_codec);
            break;
          }
          case 178: {
            if (f22_ == null) {
              F22 = new global::Google.Protobuf.WellKnownTypes.ListValue();
            }
            input.ReadMessage(F22);
            break;
          }
          case 194: {
            bool? value = _single_f24_codec.Read(input);
            if (f24_ == null || value != false) {
              F24 = value;
            }
            break;
          }
          case 202: {
            pb::ByteString value = _single_f25_codec.Read(input);
            if (f25_ == null || value != pb::ByteString.Empty) {
              F25 = value;
            }
            break;
          }
          case 210: {
            double? value = _single_f26_codec.Read(input);
            if (f26_ == null || value != 0D) {
              F26 = value;
            }
            break;
          }
          case 218: {
            int? value = _single_f27_codec.Read(input);
            if (f27_ == null || value != 0) {
              F27 = value;
            }
            break;
          }
          case 226: {
            long? value = _single_f28_codec.Read(input);
            if (f28_ == null || value != 0L) {
              F28 = value;
            }
            break;
          }
          case 232: {
            F29 = (global::Google.Protobuf.WellKnownTypes.NullValue) input.ReadEnum();
            break;
          }
          case 266: {
            if (f33_ == null) {
              F33 = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(F33);
            break;
          }
          case 274: {
            uint? value = _single_f34_codec.Read(input);
            if (f34_ == null || value != 0) {
              F34 = value;
            }
            break;
          }
          case 282: {
            ulong? value = _single_f35_codec.Read(input);
            if (f35_ == null || value != 0UL) {
              F35 = value;
            }
            break;
          }
          case 290: {
            if (f36_ == null) {
              F36 = new global::Google.Protobuf.WellKnownTypes.Value();
            }
            input.ReadMessage(F36);
            break;
          }
          case 298: {
            if (f37_ == null) {
              F37 = new global::Google.Protobuf.WellKnownTypes.Api();
            }
            input.ReadMessage(F37);
            break;
          }
          case 306: {
            if (f38_ == null) {
              F38 = new global::Google.Protobuf.WellKnownTypes.FieldMask();
            }
            input.ReadMessage(F38);
            break;
          }
          case 314: {
            if (f39_ == null) {
              F39 = new global::Google.Protobuf.WellKnownTypes.SourceContext();
            }
            input.ReadMessage(F39);
            break;
          }
          case 330: {
            if (f41_ == null) {
              F41 = new global::Google.Protobuf.WellKnownTypes.Type();
            }
            input.ReadMessage(F41);
            break;
          }
          case 338: {
            if (f42_ == null) {
              F42 = new global::Google.Protobuf.WellKnownTypes.Enum();
            }
            input.ReadMessage(F42);
            break;
          }
          case 346: {
            if (f43_ == null) {
              F43 = new global::Google.Protobuf.WellKnownTypes.EnumValue();
            }
            input.ReadMessage(F43);
            break;
          }
          case 354: {
            if (f44_ == null) {
              F44 = new global::Google.Protobuf.WellKnownTypes.Field();
            }
            input.ReadMessage(F44);
            break;
          }
          case 360: {
            F45 = (global::Google.Protobuf.WellKnownTypes.Field.Types.Cardinality) input.ReadEnum();
            break;
          }
          case 368: {
            F46 = (global::Google.Protobuf.WellKnownTypes.Field.Types.Kind) input.ReadEnum();
            break;
          }
          case 378: {
            if (f47_ == null) {
              F47 = new global::Google.Protobuf.WellKnownTypes.Method();
            }
            input.ReadMessage(F47);
            break;
          }
          case 386: {
            if (f48_ == null) {
              F48 = new global::Google.Protobuf.WellKnownTypes.Mixin();
            }
            input.ReadMessage(F48);
            break;
          }
          case 394: {
            if (f49_ == null) {
              F49 = new global::Google.Protobuf.WellKnownTypes.Option();
            }
            input.ReadMessage(F49);
            break;
          }
          case 400: {
            F50 = (global::Google.Protobuf.WellKnownTypes.Syntax) input.ReadEnum();
            break;
          }
          case 800: {
            A = input.ReadInt32();
            break;
          }
          case 810: {
            bg_.AddEntriesFrom(input, _repeated_bg_codec);
            break;
          }
          case 821: {
            Floating = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (f1_ == null) {
              F1 = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(F1);
            break;
          }
          case 18: {
            string value = _single_f2_codec.Read(ref input);
            if (f2_ == null || value != "") {
              F2 = value;
            }
            break;
          }
          case 26: {
            float? value = _single_f3_codec.Read(ref input);
            if (f3_ == null || value != 0F) {
              F3 = value;
            }
            break;
          }
          case 34: {
            if (f4_ == null) {
              F4 = new global::Google.Protobuf.WellKnownTypes.Empty();
            }
            input.ReadMessage(F4);
            break;
          }
          case 42: {
            if (f5_ == null) {
              F5 = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(F5);
            break;
          }
          case 50: {
            if (f6_ == null) {
              F6 = new global::Google.Type.Money();
            }
            input.ReadMessage(F6);
            break;
          }
          case 58: {
            if (f7_ == null) {
              F7 = new global::Google.Type.Date();
            }
            input.ReadMessage(F7);
            break;
          }
          case 66: {
            if (f8_ == null) {
              F8 = new global::Google.Type.TimeOfDay();
            }
            input.ReadMessage(F8);
            break;
          }
          case 72: {
            F9 = (global::Google.Type.CalendarPeriod) input.ReadEnum();
            break;
          }
          case 82: {
            if (f10_ == null) {
              F10 = new global::Google.Type.Color();
            }
            input.ReadMessage(F10);
            break;
          }
          case 88: {
            F11 = (global::Google.Type.DayOfWeek) input.ReadEnum();
            break;
          }
          case 98: {
            if (f12_ == null) {
              F12 = new global::Google.Type.LatLng();
            }
            input.ReadMessage(F12);
            break;
          }
          case 106: {
            if (f13_ == null) {
              F13 = new global::Google.Type.Fraction();
            }
            input.ReadMessage(F13);
            break;
          }
          case 112: {
            F14 = (global::Google.Type.Month) input.ReadEnum();
            break;
          }
          case 122: {
            if (f15_ == null) {
              F15 = new global::Google.Type.PhoneNumber();
            }
            input.ReadMessage(F15);
            break;
          }
          case 130: {
            if (f16_ == null) {
              F16 = new global::Google.Type.PostalAddress();
            }
            input.ReadMessage(F16);
            break;
          }
          case 138: {
            if (f17_ == null) {
              F17 = new global::Google.Type.LocalizedText();
            }
            input.ReadMessage(F17);
            break;
          }
          case 146: {
            f18_.AddEntriesFrom(ref input, _repeated_f18_codec);
            break;
          }
          case 154: {
            f19_.AddEntriesFrom(ref input, _repeated_f19_codec);
            break;
          }
          case 162: {
            if (f20_ == null) {
              F20 = new global::Google.Type.Expr();
            }
            input.ReadMessage(F20);
            break;
          }
          case 170: {
            f21_.AddEntriesFrom(ref input, _repeated_f21_codec);
            break;
          }
          case 178: {
            if (f22_ == null) {
              F22 = new global::Google.Protobuf.WellKnownTypes.ListValue();
            }
            input.ReadMessage(F22);
            break;
          }
          case 194: {
            bool? value = _single_f24_codec.Read(ref input);
            if (f24_ == null || value != false) {
              F24 = value;
            }
            break;
          }
          case 202: {
            pb::ByteString value = _single_f25_codec.Read(ref input);
            if (f25_ == null || value != pb::ByteString.Empty) {
              F25 = value;
            }
            break;
          }
          case 210: {
            double? value = _single_f26_codec.Read(ref input);
            if (f26_ == null || value != 0D) {
              F26 = value;
            }
            break;
          }
          case 218: {
            int? value = _single_f27_codec.Read(ref input);
            if (f27_ == null || value != 0) {
              F27 = value;
            }
            break;
          }
          case 226: {
            long? value = _single_f28_codec.Read(ref input);
            if (f28_ == null || value != 0L) {
              F28 = value;
            }
            break;
          }
          case 232: {
            F29 = (global::Google.Protobuf.WellKnownTypes.NullValue) input.ReadEnum();
            break;
          }
          case 266: {
            if (f33_ == null) {
              F33 = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(F33);
            break;
          }
          case 274: {
            uint? value = _single_f34_codec.Read(ref input);
            if (f34_ == null || value != 0) {
              F34 = value;
            }
            break;
          }
          case 282: {
            ulong? value = _single_f35_codec.Read(ref input);
            if (f35_ == null || value != 0UL) {
              F35 = value;
            }
            break;
          }
          case 290: {
            if (f36_ == null) {
              F36 = new global::Google.Protobuf.WellKnownTypes.Value();
            }
            input.ReadMessage(F36);
            break;
          }
          case 298: {
            if (f37_ == null) {
              F37 = new global::Google.Protobuf.WellKnownTypes.Api();
            }
            input.ReadMessage(F37);
            break;
          }
          case 306: {
            if (f38_ == null) {
              F38 = new global::Google.Protobuf.WellKnownTypes.FieldMask();
            }
            input.ReadMessage(F38);
            break;
          }
          case 314: {
            if (f39_ == null) {
              F39 = new global::Google.Protobuf.WellKnownTypes.SourceContext();
            }
            input.ReadMessage(F39);
            break;
          }
          case 330: {
            if (f41_ == null) {
              F41 = new global::Google.Protobuf.WellKnownTypes.Type();
            }
            input.ReadMessage(F41);
            break;
          }
          case 338: {
            if (f42_ == null) {
              F42 = new global::Google.Protobuf.WellKnownTypes.Enum();
            }
            input.ReadMessage(F42);
            break;
          }
          case 346: {
            if (f43_ == null) {
              F43 = new global::Google.Protobuf.WellKnownTypes.EnumValue();
            }
            input.ReadMessage(F43);
            break;
          }
          case 354: {
            if (f44_ == null) {
              F44 = new global::Google.Protobuf.WellKnownTypes.Field();
            }
            input.ReadMessage(F44);
            break;
          }
          case 360: {
            F45 = (global::Google.Protobuf.WellKnownTypes.Field.Types.Cardinality) input.ReadEnum();
            break;
          }
          case 368: {
            F46 = (global::Google.Protobuf.WellKnownTypes.Field.Types.Kind) input.ReadEnum();
            break;
          }
          case 378: {
            if (f47_ == null) {
              F47 = new global::Google.Protobuf.WellKnownTypes.Method();
            }
            input.ReadMessage(F47);
            break;
          }
          case 386: {
            if (f48_ == null) {
              F48 = new global::Google.Protobuf.WellKnownTypes.Mixin();
            }
            input.ReadMessage(F48);
            break;
          }
          case 394: {
            if (f49_ == null) {
              F49 = new global::Google.Protobuf.WellKnownTypes.Option();
            }
            input.ReadMessage(F49);
            break;
          }
          case 400: {
            F50 = (global::Google.Protobuf.WellKnownTypes.Syntax) input.ReadEnum();
            break;
          }
          case 800: {
            A = input.ReadInt32();
            break;
          }
          case 810: {
            bg_.AddEntriesFrom(ref input, _repeated_bg_codec);
            break;
          }
          case 821: {
            Floating = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
